// Code generated by protoc-gen-go.
// source: protobuf/index_rpc.proto
// DO NOT EDIT!

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Index service

type IndexClient interface {
	PutDocument(ctx context.Context, in *PutDocumentRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	Bulk(ctx context.Context, in *BulkRequest, opts ...grpc.CallOption) (*BulkResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	GetIndexMapping(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetIndexMappingResponse, error)
	GetIndexMeta(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetIndexMetaResponse, error)
}

type indexClient struct {
	cc *grpc.ClientConn
}

func NewIndexClient(cc *grpc.ClientConn) IndexClient {
	return &indexClient{cc}
}

func (c *indexClient) PutDocument(ctx context.Context, in *PutDocumentRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/blast.Index/PutDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	out := new(GetDocumentResponse)
	err := grpc.Invoke(ctx, "/blast.Index/GetDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/blast.Index/DeleteDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) Bulk(ctx context.Context, in *BulkRequest, opts ...grpc.CallOption) (*BulkResponse, error) {
	out := new(BulkResponse)
	err := grpc.Invoke(ctx, "/blast.Index/Bulk", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/blast.Index/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) GetIndexMapping(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetIndexMappingResponse, error) {
	out := new(GetIndexMappingResponse)
	err := grpc.Invoke(ctx, "/blast.Index/GetIndexMapping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) GetIndexMeta(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetIndexMetaResponse, error) {
	out := new(GetIndexMetaResponse)
	err := grpc.Invoke(ctx, "/blast.Index/GetIndexMeta", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Index service

type IndexServer interface {
	PutDocument(context.Context, *PutDocumentRequest) (*google_protobuf1.Empty, error)
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*google_protobuf1.Empty, error)
	Bulk(context.Context, *BulkRequest) (*BulkResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	GetIndexMapping(context.Context, *google_protobuf1.Empty) (*GetIndexMappingResponse, error)
	GetIndexMeta(context.Context, *google_protobuf1.Empty) (*GetIndexMetaResponse, error)
}

func RegisterIndexServer(s *grpc.Server, srv IndexServer) {
	s.RegisterService(&_Index_serviceDesc, srv)
}

func _Index_PutDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).PutDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blast.Index/PutDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).PutDocument(ctx, req.(*PutDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blast.Index/GetDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blast.Index/DeleteDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_Bulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).Bulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blast.Index/Bulk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).Bulk(ctx, req.(*BulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blast.Index/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_GetIndexMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetIndexMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blast.Index/GetIndexMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetIndexMapping(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_GetIndexMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetIndexMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blast.Index/GetIndexMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetIndexMeta(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Index_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blast.Index",
	HandlerType: (*IndexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutDocument",
			Handler:    _Index_PutDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _Index_GetDocument_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _Index_DeleteDocument_Handler,
		},
		{
			MethodName: "Bulk",
			Handler:    _Index_Bulk_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Index_Search_Handler,
		},
		{
			MethodName: "GetIndexMapping",
			Handler:    _Index_GetIndexMapping_Handler,
		},
		{
			MethodName: "GetIndexMeta",
			Handler:    _Index_GetIndexMeta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/index_rpc.proto",
}

func init() { proto.RegisterFile("protobuf/index_rpc.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x0b, 0xda, 0x22, 0x53, 0x51, 0x18, 0x3f, 0xd0, 0x54, 0x3c, 0xf4, 0x01, 0xb6, 0xa8,
	0x07, 0xef, 0xa1, 0xb5, 0x8a, 0x08, 0xa2, 0x37, 0x2f, 0xb2, 0x89, 0x63, 0x2c, 0x26, 0xd9, 0x35,
	0x3b, 0x0b, 0xfa, 0xb0, 0xbe, 0x8b, 0xe4, 0x63, 0xb7, 0x69, 0x35, 0x78, 0xcb, 0xfc, 0x3f, 0x7e,
	0x33, 0x59, 0x38, 0xd2, 0x85, 0x62, 0x15, 0xd9, 0xd7, 0xc9, 0x22, 0x7f, 0xa1, 0xcf, 0xe7, 0x42,
	0xc7, 0xa2, 0x92, 0xb0, 0x1f, 0xa5, 0xd2, 0x70, 0x70, 0xe8, 0x03, 0x19, 0x19, 0x23, 0x13, 0xaa,
	0xed, 0x60, 0x94, 0x28, 0x95, 0xa4, 0x34, 0xf1, 0x36, 0x65, 0x9a, 0xbf, 0x6a, 0xf3, 0xfc, 0x7b,
	0x03, 0xfa, 0x37, 0x25, 0x0f, 0x43, 0x18, 0xde, 0x5b, 0x9e, 0xaa, 0xd8, 0x66, 0x94, 0x33, 0x1e,
	0x8b, 0x8a, 0x2a, 0x5a, 0xda, 0x03, 0x7d, 0x58, 0x2a, 0x17, 0x89, 0x9a, 0x28, 0x1c, 0x51, 0xcc,
	0x4a, 0xe2, 0xb8, 0x87, 0x57, 0x30, 0x9c, 0xd3, 0x6f, 0x46, 0x4b, 0x73, 0x8c, 0xe0, 0x2f, 0xcb,
	0x68, 0x95, 0x1b, 0x1a, 0xf7, 0xf0, 0x1a, 0x76, 0xa6, 0x94, 0x12, 0x93, 0x47, 0x9d, 0x34, 0xf9,
	0x55, 0xf9, 0xff, 0x8b, 0xce, 0x60, 0x33, 0xb4, 0xe9, 0x3b, 0x62, 0xd3, 0x2f, 0x07, 0xd7, 0xda,
	0x5b, 0xd1, 0xfc, 0xf2, 0x4b, 0x18, 0x3c, 0x92, 0x2c, 0xe2, 0x37, 0xdc, 0x6f, 0x02, 0xf5, 0xe8,
	0x6a, 0x07, 0x6b, 0xaa, 0x2f, 0xde, 0xc2, 0xee, 0x9c, 0xb8, 0x7a, 0xcd, 0x3b, 0xa9, 0xf5, 0x22,
	0x4f, 0xb0, 0xe3, 0xb0, 0xe0, 0x74, 0xf9, 0xfb, 0xed, 0x7c, 0x0b, 0x36, 0x83, 0x6d, 0x6f, 0x12,
	0xcb, 0x4e, 0xd2, 0x68, 0x9d, 0x44, 0x2c, 0x97, 0x98, 0x10, 0x9e, 0xb6, 0x5c, 0x21, 0x1a, 0x54,
	0x5f, 0x17, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x86, 0x9b, 0xe9, 0xe0, 0x4a, 0x02, 0x00, 0x00,
}
