// Code generated by protoc-gen-go.
// source: protobuf/message.proto
// DO NOT EDIT!

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"
import _ "github.com/golang/protobuf/ptypes/empty"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PutDocumentRequest struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *PutDocumentRequest) Reset()                    { *m = PutDocumentRequest{} }
func (m *PutDocumentRequest) String() string            { return proto.CompactTextString(m) }
func (*PutDocumentRequest) ProtoMessage()               {}
func (*PutDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *PutDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutDocumentRequest) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type GetDocumentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetDocumentRequest) Reset()                    { *m = GetDocumentRequest{} }
func (m *GetDocumentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDocumentRequest) ProtoMessage()               {}
func (*GetDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *GetDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetDocumentResponse struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *GetDocumentResponse) Reset()                    { *m = GetDocumentResponse{} }
func (m *GetDocumentResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDocumentResponse) ProtoMessage()               {}
func (*GetDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *GetDocumentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetDocumentResponse) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type DeleteDocumentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteDocumentRequest) Reset()                    { *m = DeleteDocumentRequest{} }
func (m *DeleteDocumentRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDocumentRequest) ProtoMessage()               {}
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *DeleteDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type BulkRequest struct {
	BatchSize int32                  `protobuf:"varint,1,opt,name=batch_size,json=batchSize" json:"batch_size,omitempty"`
	Requests  []*BulkRequest_Request `protobuf:"bytes,2,rep,name=requests" json:"requests,omitempty"`
}

func (m *BulkRequest) Reset()                    { *m = BulkRequest{} }
func (m *BulkRequest) String() string            { return proto.CompactTextString(m) }
func (*BulkRequest) ProtoMessage()               {}
func (*BulkRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *BulkRequest) GetBatchSize() int32 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

func (m *BulkRequest) GetRequests() []*BulkRequest_Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

type BulkRequest_Request struct {
	Method   string                        `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Document *BulkRequest_Request_Document `protobuf:"bytes,2,opt,name=document" json:"document,omitempty"`
}

func (m *BulkRequest_Request) Reset()                    { *m = BulkRequest_Request{} }
func (m *BulkRequest_Request) String() string            { return proto.CompactTextString(m) }
func (*BulkRequest_Request) ProtoMessage()               {}
func (*BulkRequest_Request) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4, 0} }

func (m *BulkRequest_Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *BulkRequest_Request) GetDocument() *BulkRequest_Request_Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type BulkRequest_Request_Document struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *BulkRequest_Request_Document) Reset()         { *m = BulkRequest_Request_Document{} }
func (m *BulkRequest_Request_Document) String() string { return proto.CompactTextString(m) }
func (*BulkRequest_Request_Document) ProtoMessage()    {}
func (*BulkRequest_Request_Document) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{4, 0, 0}
}

func (m *BulkRequest_Request_Document) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BulkRequest_Request_Document) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type BulkResponse struct {
	PutCount    int32 `protobuf:"varint,1,opt,name=put_count,json=putCount" json:"put_count,omitempty"`
	DeleteCount int32 `protobuf:"varint,2,opt,name=delete_count,json=deleteCount" json:"delete_count,omitempty"`
	ErrorCount  int32 `protobuf:"varint,3,opt,name=error_count,json=errorCount" json:"error_count,omitempty"`
}

func (m *BulkResponse) Reset()                    { *m = BulkResponse{} }
func (m *BulkResponse) String() string            { return proto.CompactTextString(m) }
func (*BulkResponse) ProtoMessage()               {}
func (*BulkResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *BulkResponse) GetPutCount() int32 {
	if m != nil {
		return m.PutCount
	}
	return 0
}

func (m *BulkResponse) GetDeleteCount() int32 {
	if m != nil {
		return m.DeleteCount
	}
	return 0
}

func (m *BulkResponse) GetErrorCount() int32 {
	if m != nil {
		return m.ErrorCount
	}
	return 0
}

type SearchRequest struct {
	SearchRequest *google_protobuf.Any `protobuf:"bytes,1,opt,name=search_request,json=searchRequest" json:"search_request,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *SearchRequest) GetSearchRequest() *google_protobuf.Any {
	if m != nil {
		return m.SearchRequest
	}
	return nil
}

type SearchResponse struct {
	SearchResult *google_protobuf.Any `protobuf:"bytes,1,opt,name=search_result,json=searchResult" json:"search_result,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *SearchResponse) GetSearchResult() *google_protobuf.Any {
	if m != nil {
		return m.SearchResult
	}
	return nil
}

type NodeInfo struct {
	Role      string `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	Status    string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	Timestamp string `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *NodeInfo) Reset()                    { *m = NodeInfo{} }
func (m *NodeInfo) String() string            { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()               {}
func (*NodeInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *NodeInfo) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *NodeInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *NodeInfo) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type PutNodeRequest struct {
	Cluster  string    `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Node     string    `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
	NodeInfo *NodeInfo `protobuf:"bytes,3,opt,name=node_info,json=nodeInfo" json:"node_info,omitempty"`
}

func (m *PutNodeRequest) Reset()                    { *m = PutNodeRequest{} }
func (m *PutNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*PutNodeRequest) ProtoMessage()               {}
func (*PutNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *PutNodeRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *PutNodeRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *PutNodeRequest) GetNodeInfo() *NodeInfo {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

type GetNodeRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Node    string `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
}

func (m *GetNodeRequest) Reset()                    { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()               {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *GetNodeRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *GetNodeRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type GetNodeResponse struct {
	NodeInfo *NodeInfo `protobuf:"bytes,1,opt,name=node_info,json=nodeInfo" json:"node_info,omitempty"`
}

func (m *GetNodeResponse) Reset()                    { *m = GetNodeResponse{} }
func (m *GetNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNodeResponse) ProtoMessage()               {}
func (*GetNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *GetNodeResponse) GetNodeInfo() *NodeInfo {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

type DeleteNodeRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Node    string `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
}

func (m *DeleteNodeRequest) Reset()                    { *m = DeleteNodeRequest{} }
func (m *DeleteNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteNodeRequest) ProtoMessage()               {}
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *DeleteNodeRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *DeleteNodeRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type PutIndexMappingRequest struct {
	Cluster      string               `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	IndexMapping *google_protobuf.Any `protobuf:"bytes,2,opt,name=index_mapping,json=indexMapping" json:"index_mapping,omitempty"`
}

func (m *PutIndexMappingRequest) Reset()                    { *m = PutIndexMappingRequest{} }
func (m *PutIndexMappingRequest) String() string            { return proto.CompactTextString(m) }
func (*PutIndexMappingRequest) ProtoMessage()               {}
func (*PutIndexMappingRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *PutIndexMappingRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *PutIndexMappingRequest) GetIndexMapping() *google_protobuf.Any {
	if m != nil {
		return m.IndexMapping
	}
	return nil
}

type GetIndexMappingRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
}

func (m *GetIndexMappingRequest) Reset()                    { *m = GetIndexMappingRequest{} }
func (m *GetIndexMappingRequest) String() string            { return proto.CompactTextString(m) }
func (*GetIndexMappingRequest) ProtoMessage()               {}
func (*GetIndexMappingRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{14} }

func (m *GetIndexMappingRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

type GetIndexMappingResponse struct {
	IndexMapping *google_protobuf.Any `protobuf:"bytes,1,opt,name=index_mapping,json=indexMapping" json:"index_mapping,omitempty"`
}

func (m *GetIndexMappingResponse) Reset()                    { *m = GetIndexMappingResponse{} }
func (m *GetIndexMappingResponse) String() string            { return proto.CompactTextString(m) }
func (*GetIndexMappingResponse) ProtoMessage()               {}
func (*GetIndexMappingResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{15} }

func (m *GetIndexMappingResponse) GetIndexMapping() *google_protobuf.Any {
	if m != nil {
		return m.IndexMapping
	}
	return nil
}

type DeleteIndexMappingRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
}

func (m *DeleteIndexMappingRequest) Reset()                    { *m = DeleteIndexMappingRequest{} }
func (m *DeleteIndexMappingRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteIndexMappingRequest) ProtoMessage()               {}
func (*DeleteIndexMappingRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{16} }

func (m *DeleteIndexMappingRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

type PutIndexMetaRequest struct {
	Cluster   string               `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	IndexMeta *google_protobuf.Any `protobuf:"bytes,2,opt,name=index_meta,json=indexMeta" json:"index_meta,omitempty"`
}

func (m *PutIndexMetaRequest) Reset()                    { *m = PutIndexMetaRequest{} }
func (m *PutIndexMetaRequest) String() string            { return proto.CompactTextString(m) }
func (*PutIndexMetaRequest) ProtoMessage()               {}
func (*PutIndexMetaRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{17} }

func (m *PutIndexMetaRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *PutIndexMetaRequest) GetIndexMeta() *google_protobuf.Any {
	if m != nil {
		return m.IndexMeta
	}
	return nil
}

type GetIndexMetaRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
}

func (m *GetIndexMetaRequest) Reset()                    { *m = GetIndexMetaRequest{} }
func (m *GetIndexMetaRequest) String() string            { return proto.CompactTextString(m) }
func (*GetIndexMetaRequest) ProtoMessage()               {}
func (*GetIndexMetaRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{18} }

func (m *GetIndexMetaRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

type GetIndexMetaResponse struct {
	IndexMeta *google_protobuf.Any `protobuf:"bytes,1,opt,name=index_meta,json=indexMeta" json:"index_meta,omitempty"`
}

func (m *GetIndexMetaResponse) Reset()                    { *m = GetIndexMetaResponse{} }
func (m *GetIndexMetaResponse) String() string            { return proto.CompactTextString(m) }
func (*GetIndexMetaResponse) ProtoMessage()               {}
func (*GetIndexMetaResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{19} }

func (m *GetIndexMetaResponse) GetIndexMeta() *google_protobuf.Any {
	if m != nil {
		return m.IndexMeta
	}
	return nil
}

type DeleteIndexMetaRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
}

func (m *DeleteIndexMetaRequest) Reset()                    { *m = DeleteIndexMetaRequest{} }
func (m *DeleteIndexMetaRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteIndexMetaRequest) ProtoMessage()               {}
func (*DeleteIndexMetaRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{20} }

func (m *DeleteIndexMetaRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func init() {
	proto.RegisterType((*PutDocumentRequest)(nil), "blast.PutDocumentRequest")
	proto.RegisterType((*GetDocumentRequest)(nil), "blast.GetDocumentRequest")
	proto.RegisterType((*GetDocumentResponse)(nil), "blast.GetDocumentResponse")
	proto.RegisterType((*DeleteDocumentRequest)(nil), "blast.DeleteDocumentRequest")
	proto.RegisterType((*BulkRequest)(nil), "blast.BulkRequest")
	proto.RegisterType((*BulkRequest_Request)(nil), "blast.BulkRequest.Request")
	proto.RegisterType((*BulkRequest_Request_Document)(nil), "blast.BulkRequest.Request.Document")
	proto.RegisterType((*BulkResponse)(nil), "blast.BulkResponse")
	proto.RegisterType((*SearchRequest)(nil), "blast.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "blast.SearchResponse")
	proto.RegisterType((*NodeInfo)(nil), "blast.NodeInfo")
	proto.RegisterType((*PutNodeRequest)(nil), "blast.PutNodeRequest")
	proto.RegisterType((*GetNodeRequest)(nil), "blast.GetNodeRequest")
	proto.RegisterType((*GetNodeResponse)(nil), "blast.GetNodeResponse")
	proto.RegisterType((*DeleteNodeRequest)(nil), "blast.DeleteNodeRequest")
	proto.RegisterType((*PutIndexMappingRequest)(nil), "blast.PutIndexMappingRequest")
	proto.RegisterType((*GetIndexMappingRequest)(nil), "blast.GetIndexMappingRequest")
	proto.RegisterType((*GetIndexMappingResponse)(nil), "blast.GetIndexMappingResponse")
	proto.RegisterType((*DeleteIndexMappingRequest)(nil), "blast.DeleteIndexMappingRequest")
	proto.RegisterType((*PutIndexMetaRequest)(nil), "blast.PutIndexMetaRequest")
	proto.RegisterType((*GetIndexMetaRequest)(nil), "blast.GetIndexMetaRequest")
	proto.RegisterType((*GetIndexMetaResponse)(nil), "blast.GetIndexMetaResponse")
	proto.RegisterType((*DeleteIndexMetaRequest)(nil), "blast.DeleteIndexMetaRequest")
}

func init() { proto.RegisterFile("protobuf/message.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 625 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0x51, 0x4f, 0xdb, 0x3c,
	0x14, 0x55, 0xca, 0x07, 0x24, 0x37, 0x6d, 0xd1, 0x67, 0x58, 0x07, 0x65, 0xd3, 0x98, 0x37, 0x69,
	0x3c, 0xa0, 0x20, 0x15, 0x6d, 0x12, 0x9a, 0x34, 0x04, 0x43, 0x62, 0x88, 0x6d, 0x42, 0x29, 0x4f,
	0x7b, 0xa9, 0xd2, 0xe6, 0xb6, 0x8d, 0x96, 0xc4, 0x59, 0x6c, 0x4b, 0x83, 0xbf, 0xb1, 0xbf, 0xb1,
	0x1f, 0x39, 0xc5, 0xb1, 0x43, 0xbb, 0x89, 0xb6, 0xc0, 0x53, 0xec, 0x7b, 0xcf, 0x3d, 0xe7, 0xdc,
	0x93, 0xb4, 0xd0, 0xca, 0x72, 0x26, 0x58, 0x5f, 0x0e, 0xf7, 0x13, 0xe4, 0x3c, 0x18, 0xa1, 0xa7,
	0x0a, 0x64, 0xb9, 0x1f, 0x07, 0x5c, 0xb4, 0xb7, 0x46, 0x8c, 0x8d, 0x62, 0xdc, 0xaf, 0x50, 0x41,
	0x7a, 0x5d, 0x22, 0xda, 0xdb, 0x7f, 0xb7, 0x30, 0xc9, 0x84, 0x6e, 0x52, 0x1f, 0xc8, 0xa5, 0x14,
	0xa7, 0x6c, 0x20, 0x13, 0x4c, 0x85, 0x8f, 0x3f, 0x24, 0x72, 0x41, 0x9a, 0x50, 0x8b, 0xc2, 0x4d,
	0x6b, 0xc7, 0xda, 0x75, 0xfc, 0x5a, 0x14, 0x92, 0x3d, 0x58, 0x19, 0x46, 0x18, 0x87, 0x7c, 0xb3,
	0xb6, 0x63, 0xed, 0xba, 0x9d, 0x0d, 0xaf, 0xe4, 0xf4, 0x0c, 0xa7, 0x77, 0x9c, 0x5e, 0xfb, 0x1a,
	0x43, 0x5f, 0x03, 0x39, 0xc3, 0x79, 0x9c, 0xb4, 0x0b, 0xeb, 0x53, 0x28, 0x9e, 0xb1, 0x94, 0xe3,
	0x23, 0xa5, 0xdf, 0xc0, 0x93, 0x53, 0x8c, 0x51, 0xe0, 0x3c, 0xf5, 0x5f, 0x35, 0x70, 0x4f, 0x64,
	0xfc, 0xdd, 0xf4, 0x9f, 0x03, 0xf4, 0x03, 0x31, 0x18, 0xf7, 0x78, 0x74, 0x83, 0x0a, 0xb7, 0xec,
	0x3b, 0xaa, 0xd2, 0x8d, 0x6e, 0x90, 0xbc, 0x03, 0x3b, 0x2f, 0x91, 0x85, 0x8f, 0xa5, 0x5d, 0xb7,
	0xd3, 0xf6, 0x54, 0xf0, 0xde, 0x04, 0x89, 0xa7, 0x9f, 0x7e, 0x85, 0x6d, 0xff, 0xb6, 0x60, 0xd5,
	0x48, 0xb4, 0x60, 0x25, 0x41, 0x31, 0x66, 0xc6, 0x86, 0xbe, 0x91, 0x23, 0xb0, 0x43, 0xed, 0x56,
	0xef, 0xf8, 0xea, 0x6e, 0x6e, 0xaf, 0x5a, 0xac, 0x1a, 0x6a, 0x7f, 0x02, 0xdb, 0x54, 0x1f, 0x19,
	0x1f, 0x83, 0x7a, 0xa9, 0xa9, 0x5f, 0xc6, 0x36, 0x38, 0x99, 0x14, 0xbd, 0x01, 0x93, 0xa9, 0xd0,
	0xa1, 0xd8, 0x99, 0x14, 0x1f, 0x8b, 0x3b, 0x79, 0x09, 0xf5, 0x50, 0x65, 0xad, 0xfb, 0x35, 0xd5,
	0x77, 0xcb, 0x5a, 0x09, 0x79, 0x01, 0x2e, 0xe6, 0x39, 0xcb, 0x35, 0x62, 0x49, 0x21, 0x40, 0x95,
	0x14, 0x80, 0x7e, 0x86, 0x46, 0x17, 0x83, 0x7c, 0x30, 0x36, 0x21, 0xbd, 0x87, 0x26, 0x57, 0x85,
	0x9e, 0xce, 0x50, 0xc9, 0xde, 0xe5, 0xbb, 0xc1, 0x27, 0x87, 0xe9, 0x05, 0x34, 0x0d, 0x9b, 0x5e,
	0xe0, 0x10, 0x1a, 0x15, 0x1d, 0x97, 0xf1, 0x6c, 0xb6, 0xba, 0x61, 0x2b, 0x90, 0xf4, 0x0a, 0xec,
	0xaf, 0x2c, 0xc4, 0xf3, 0x74, 0xc8, 0x08, 0x81, 0xff, 0x72, 0x16, 0xa3, 0xce, 0x55, 0x9d, 0x8b,
	0xd7, 0xc9, 0x45, 0x20, 0x64, 0x99, 0xac, 0xe3, 0xeb, 0x1b, 0x79, 0x06, 0x8e, 0x88, 0x12, 0xe4,
	0x22, 0x48, 0x32, 0xb5, 0xb1, 0xe3, 0xdf, 0x16, 0x68, 0x0c, 0xcd, 0x4b, 0x29, 0x0a, 0x62, 0xb3,
	0xf1, 0x26, 0xac, 0x0e, 0x62, 0xc9, 0x05, 0xe6, 0x9a, 0xde, 0x5c, 0x0b, 0xd5, 0x94, 0x85, 0xa8,
	0xf9, 0xd5, 0x99, 0xec, 0x81, 0x53, 0x3c, 0x7b, 0x51, 0x3a, 0x64, 0x8a, 0xdd, 0xed, 0xac, 0xe9,
	0xaf, 0xc5, 0xb8, 0xf5, 0xed, 0x54, 0x9f, 0xe8, 0x07, 0x68, 0x9e, 0xe1, 0xc3, 0xd5, 0xe8, 0x11,
	0xac, 0x55, 0xf3, 0x3a, 0xd1, 0x29, 0x03, 0xd6, 0x3c, 0x03, 0xc7, 0xf0, 0x7f, 0xf9, 0x7b, 0x7c,
	0xb8, 0x87, 0x04, 0x5a, 0x97, 0x52, 0x9c, 0xa7, 0x21, 0xfe, 0xfc, 0x12, 0x64, 0x59, 0x94, 0x8e,
	0xe6, 0xf3, 0x1c, 0x42, 0x23, 0x2a, 0x06, 0x7a, 0x49, 0x39, 0x31, 0xf3, 0xe3, 0xaf, 0x47, 0x13,
	0xdc, 0xb4, 0x03, 0xad, 0x33, 0xbc, 0x9f, 0x1c, 0xbd, 0x82, 0xa7, 0xff, 0xcc, 0xdc, 0x7e, 0x80,
	0xd3, 0x4e, 0xac, 0x85, 0x9d, 0xbc, 0x85, 0xad, 0x32, 0xbb, 0xfb, 0x99, 0x09, 0x61, 0xbd, 0xca,
	0x0b, 0x45, 0x30, 0x3f, 0xac, 0x03, 0x00, 0x6d, 0x11, 0x45, 0x30, 0x33, 0x29, 0x27, 0x32, 0xac,
	0x74, 0x5f, 0xfd, 0x7b, 0x2f, 0xae, 0x42, 0x2f, 0x60, 0x63, 0x7a, 0x40, 0x07, 0x34, 0xad, 0x6e,
	0x2d, 0xa6, 0xde, 0x81, 0xd6, 0x64, 0x34, 0x8b, 0x18, 0x38, 0x81, 0x6f, 0xb6, 0xa1, 0xeb, 0xaf,
	0xa8, 0xd3, 0xc1, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xb4, 0x06, 0x76, 0x55, 0x07, 0x00,
	0x00,
}
