// Code generated by protoc-gen-go.
// source: protobuf/message.proto
// DO NOT EDIT!

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"
import _ "github.com/golang/protobuf/ptypes/empty"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PutDocumentRequest struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *PutDocumentRequest) Reset()                    { *m = PutDocumentRequest{} }
func (m *PutDocumentRequest) String() string            { return proto.CompactTextString(m) }
func (*PutDocumentRequest) ProtoMessage()               {}
func (*PutDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *PutDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutDocumentRequest) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type PutDocumentResponse struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *PutDocumentResponse) Reset()                    { *m = PutDocumentResponse{} }
func (m *PutDocumentResponse) String() string            { return proto.CompactTextString(m) }
func (*PutDocumentResponse) ProtoMessage()               {}
func (*PutDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *PutDocumentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutDocumentResponse) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type GetDocumentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetDocumentRequest) Reset()                    { *m = GetDocumentRequest{} }
func (m *GetDocumentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDocumentRequest) ProtoMessage()               {}
func (*GetDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *GetDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetDocumentResponse struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *GetDocumentResponse) Reset()                    { *m = GetDocumentResponse{} }
func (m *GetDocumentResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDocumentResponse) ProtoMessage()               {}
func (*GetDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *GetDocumentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetDocumentResponse) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type DeleteDocumentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteDocumentRequest) Reset()                    { *m = DeleteDocumentRequest{} }
func (m *DeleteDocumentRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDocumentRequest) ProtoMessage()               {}
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *DeleteDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteDocumentResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteDocumentResponse) Reset()                    { *m = DeleteDocumentResponse{} }
func (m *DeleteDocumentResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteDocumentResponse) ProtoMessage()               {}
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *DeleteDocumentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type BulkRequest struct {
	BatchSize      int32                        `protobuf:"varint,1,opt,name=batch_size,json=batchSize" json:"batch_size,omitempty"`
	UpdateRequests []*BulkRequest_UpdateRequest `protobuf:"bytes,2,rep,name=update_requests,json=updateRequests" json:"update_requests,omitempty"`
}

func (m *BulkRequest) Reset()                    { *m = BulkRequest{} }
func (m *BulkRequest) String() string            { return proto.CompactTextString(m) }
func (*BulkRequest) ProtoMessage()               {}
func (*BulkRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *BulkRequest) GetBatchSize() int32 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

func (m *BulkRequest) GetUpdateRequests() []*BulkRequest_UpdateRequest {
	if m != nil {
		return m.UpdateRequests
	}
	return nil
}

type BulkRequest_UpdateRequest struct {
	Method   string                              `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Document *BulkRequest_UpdateRequest_Document `protobuf:"bytes,2,opt,name=document" json:"document,omitempty"`
}

func (m *BulkRequest_UpdateRequest) Reset()                    { *m = BulkRequest_UpdateRequest{} }
func (m *BulkRequest_UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*BulkRequest_UpdateRequest) ProtoMessage()               {}
func (*BulkRequest_UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6, 0} }

func (m *BulkRequest_UpdateRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *BulkRequest_UpdateRequest) GetDocument() *BulkRequest_UpdateRequest_Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type BulkRequest_UpdateRequest_Document struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *BulkRequest_UpdateRequest_Document) Reset()         { *m = BulkRequest_UpdateRequest_Document{} }
func (m *BulkRequest_UpdateRequest_Document) String() string { return proto.CompactTextString(m) }
func (*BulkRequest_UpdateRequest_Document) ProtoMessage()    {}
func (*BulkRequest_UpdateRequest_Document) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{6, 0, 0}
}

func (m *BulkRequest_UpdateRequest_Document) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BulkRequest_UpdateRequest_Document) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type BulkResponse struct {
	PutCount         int32 `protobuf:"varint,1,opt,name=put_count,json=putCount" json:"put_count,omitempty"`
	PutErrorCount    int32 `protobuf:"varint,2,opt,name=put_error_count,json=putErrorCount" json:"put_error_count,omitempty"`
	DeleteCount      int32 `protobuf:"varint,3,opt,name=delete_count,json=deleteCount" json:"delete_count,omitempty"`
	MethodErrorCount int32 `protobuf:"varint,4,opt,name=method_error_count,json=methodErrorCount" json:"method_error_count,omitempty"`
}

func (m *BulkResponse) Reset()                    { *m = BulkResponse{} }
func (m *BulkResponse) String() string            { return proto.CompactTextString(m) }
func (*BulkResponse) ProtoMessage()               {}
func (*BulkResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *BulkResponse) GetPutCount() int32 {
	if m != nil {
		return m.PutCount
	}
	return 0
}

func (m *BulkResponse) GetPutErrorCount() int32 {
	if m != nil {
		return m.PutErrorCount
	}
	return 0
}

func (m *BulkResponse) GetDeleteCount() int32 {
	if m != nil {
		return m.DeleteCount
	}
	return 0
}

func (m *BulkResponse) GetMethodErrorCount() int32 {
	if m != nil {
		return m.MethodErrorCount
	}
	return 0
}

type SearchRequest struct {
	SearchRequest *google_protobuf.Any `protobuf:"bytes,1,opt,name=search_request,json=searchRequest" json:"search_request,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *SearchRequest) GetSearchRequest() *google_protobuf.Any {
	if m != nil {
		return m.SearchRequest
	}
	return nil
}

type SearchResponse struct {
	SearchResult *google_protobuf.Any `protobuf:"bytes,1,opt,name=search_result,json=searchResult" json:"search_result,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *SearchResponse) GetSearchResult() *google_protobuf.Any {
	if m != nil {
		return m.SearchResult
	}
	return nil
}

type PutNodeRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Node    string `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
}

func (m *PutNodeRequest) Reset()                    { *m = PutNodeRequest{} }
func (m *PutNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*PutNodeRequest) ProtoMessage()               {}
func (*PutNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *PutNodeRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *PutNodeRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type GetNodeRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Node    string `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
}

func (m *GetNodeRequest) Reset()                    { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()               {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *GetNodeRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *GetNodeRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type GetNodeResponse struct {
	Value *google_protobuf.Any `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *GetNodeResponse) Reset()                    { *m = GetNodeResponse{} }
func (m *GetNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNodeResponse) ProtoMessage()               {}
func (*GetNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *GetNodeResponse) GetValue() *google_protobuf.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type DeleteNodeRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Node    string `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
}

func (m *DeleteNodeRequest) Reset()                    { *m = DeleteNodeRequest{} }
func (m *DeleteNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteNodeRequest) ProtoMessage()               {}
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *DeleteNodeRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *DeleteNodeRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type PutIndexMappingRequest struct {
	Cluster      string               `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	IndexMapping *google_protobuf.Any `protobuf:"bytes,2,opt,name=index_mapping,json=indexMapping" json:"index_mapping,omitempty"`
}

func (m *PutIndexMappingRequest) Reset()                    { *m = PutIndexMappingRequest{} }
func (m *PutIndexMappingRequest) String() string            { return proto.CompactTextString(m) }
func (*PutIndexMappingRequest) ProtoMessage()               {}
func (*PutIndexMappingRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{14} }

func (m *PutIndexMappingRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *PutIndexMappingRequest) GetIndexMapping() *google_protobuf.Any {
	if m != nil {
		return m.IndexMapping
	}
	return nil
}

type GetIndexMappingRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
}

func (m *GetIndexMappingRequest) Reset()                    { *m = GetIndexMappingRequest{} }
func (m *GetIndexMappingRequest) String() string            { return proto.CompactTextString(m) }
func (*GetIndexMappingRequest) ProtoMessage()               {}
func (*GetIndexMappingRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{15} }

func (m *GetIndexMappingRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

type GetIndexMappingResponse struct {
	IndexMapping *google_protobuf.Any `protobuf:"bytes,1,opt,name=index_mapping,json=indexMapping" json:"index_mapping,omitempty"`
}

func (m *GetIndexMappingResponse) Reset()                    { *m = GetIndexMappingResponse{} }
func (m *GetIndexMappingResponse) String() string            { return proto.CompactTextString(m) }
func (*GetIndexMappingResponse) ProtoMessage()               {}
func (*GetIndexMappingResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{16} }

func (m *GetIndexMappingResponse) GetIndexMapping() *google_protobuf.Any {
	if m != nil {
		return m.IndexMapping
	}
	return nil
}

type DeleteIndexMappingRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
}

func (m *DeleteIndexMappingRequest) Reset()                    { *m = DeleteIndexMappingRequest{} }
func (m *DeleteIndexMappingRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteIndexMappingRequest) ProtoMessage()               {}
func (*DeleteIndexMappingRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{17} }

func (m *DeleteIndexMappingRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

type PutIndexMetaRequest struct {
	Cluster   string               `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	IndexMeta *google_protobuf.Any `protobuf:"bytes,2,opt,name=index_meta,json=indexMeta" json:"index_meta,omitempty"`
}

func (m *PutIndexMetaRequest) Reset()                    { *m = PutIndexMetaRequest{} }
func (m *PutIndexMetaRequest) String() string            { return proto.CompactTextString(m) }
func (*PutIndexMetaRequest) ProtoMessage()               {}
func (*PutIndexMetaRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{18} }

func (m *PutIndexMetaRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *PutIndexMetaRequest) GetIndexMeta() *google_protobuf.Any {
	if m != nil {
		return m.IndexMeta
	}
	return nil
}

type GetIndexMetaRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
}

func (m *GetIndexMetaRequest) Reset()                    { *m = GetIndexMetaRequest{} }
func (m *GetIndexMetaRequest) String() string            { return proto.CompactTextString(m) }
func (*GetIndexMetaRequest) ProtoMessage()               {}
func (*GetIndexMetaRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{19} }

func (m *GetIndexMetaRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

type GetIndexMetaResponse struct {
	IndexMeta *google_protobuf.Any `protobuf:"bytes,1,opt,name=index_meta,json=indexMeta" json:"index_meta,omitempty"`
}

func (m *GetIndexMetaResponse) Reset()                    { *m = GetIndexMetaResponse{} }
func (m *GetIndexMetaResponse) String() string            { return proto.CompactTextString(m) }
func (*GetIndexMetaResponse) ProtoMessage()               {}
func (*GetIndexMetaResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{20} }

func (m *GetIndexMetaResponse) GetIndexMeta() *google_protobuf.Any {
	if m != nil {
		return m.IndexMeta
	}
	return nil
}

type DeleteIndexMetaRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
}

func (m *DeleteIndexMetaRequest) Reset()                    { *m = DeleteIndexMetaRequest{} }
func (m *DeleteIndexMetaRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteIndexMetaRequest) ProtoMessage()               {}
func (*DeleteIndexMetaRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{21} }

func (m *DeleteIndexMetaRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func init() {
	proto.RegisterType((*PutDocumentRequest)(nil), "blast.PutDocumentRequest")
	proto.RegisterType((*PutDocumentResponse)(nil), "blast.PutDocumentResponse")
	proto.RegisterType((*GetDocumentRequest)(nil), "blast.GetDocumentRequest")
	proto.RegisterType((*GetDocumentResponse)(nil), "blast.GetDocumentResponse")
	proto.RegisterType((*DeleteDocumentRequest)(nil), "blast.DeleteDocumentRequest")
	proto.RegisterType((*DeleteDocumentResponse)(nil), "blast.DeleteDocumentResponse")
	proto.RegisterType((*BulkRequest)(nil), "blast.BulkRequest")
	proto.RegisterType((*BulkRequest_UpdateRequest)(nil), "blast.BulkRequest.UpdateRequest")
	proto.RegisterType((*BulkRequest_UpdateRequest_Document)(nil), "blast.BulkRequest.UpdateRequest.Document")
	proto.RegisterType((*BulkResponse)(nil), "blast.BulkResponse")
	proto.RegisterType((*SearchRequest)(nil), "blast.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "blast.SearchResponse")
	proto.RegisterType((*PutNodeRequest)(nil), "blast.PutNodeRequest")
	proto.RegisterType((*GetNodeRequest)(nil), "blast.GetNodeRequest")
	proto.RegisterType((*GetNodeResponse)(nil), "blast.GetNodeResponse")
	proto.RegisterType((*DeleteNodeRequest)(nil), "blast.DeleteNodeRequest")
	proto.RegisterType((*PutIndexMappingRequest)(nil), "blast.PutIndexMappingRequest")
	proto.RegisterType((*GetIndexMappingRequest)(nil), "blast.GetIndexMappingRequest")
	proto.RegisterType((*GetIndexMappingResponse)(nil), "blast.GetIndexMappingResponse")
	proto.RegisterType((*DeleteIndexMappingRequest)(nil), "blast.DeleteIndexMappingRequest")
	proto.RegisterType((*PutIndexMetaRequest)(nil), "blast.PutIndexMetaRequest")
	proto.RegisterType((*GetIndexMetaRequest)(nil), "blast.GetIndexMetaRequest")
	proto.RegisterType((*GetIndexMetaResponse)(nil), "blast.GetIndexMetaResponse")
	proto.RegisterType((*DeleteIndexMetaRequest)(nil), "blast.DeleteIndexMetaRequest")
}

func init() { proto.RegisterFile("protobuf/message.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 612 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x6f, 0x12, 0x41,
	0x14, 0xcd, 0xd2, 0x0f, 0xe1, 0xc2, 0x52, 0x1d, 0x2b, 0xb6, 0x34, 0x26, 0x75, 0x63, 0x14, 0x4d,
	0xb3, 0x24, 0x34, 0x3e, 0x34, 0x46, 0x93, 0xd6, 0x36, 0xd8, 0x54, 0x0d, 0x59, 0xf4, 0xc5, 0x17,
	0xb2, 0xb0, 0xb7, 0xb0, 0x71, 0xbf, 0xdc, 0x99, 0x31, 0xb6, 0xbf, 0xc7, 0x5f, 0xe0, 0x93, 0x3f,
	0xcf, 0xec, 0x7c, 0x6c, 0xd9, 0xaa, 0x40, 0xc5, 0xb7, 0x9d, 0x3b, 0xe7, 0x9c, 0x7b, 0xee, 0xb9,
	0x30, 0xd0, 0x48, 0xd2, 0x98, 0xc5, 0x43, 0x7e, 0xde, 0x0e, 0x91, 0x52, 0x77, 0x8c, 0xb6, 0x28,
	0x90, 0xb5, 0x61, 0xe0, 0x52, 0xd6, 0xdc, 0x1e, 0xc7, 0xf1, 0x38, 0xc0, 0x76, 0x8e, 0x72, 0xa3,
	0x0b, 0x89, 0x68, 0xee, 0x5c, 0xbf, 0xc2, 0x30, 0x61, 0xea, 0xd2, 0x72, 0x80, 0xf4, 0x38, 0x3b,
	0x8e, 0x47, 0x3c, 0xc4, 0x88, 0x39, 0xf8, 0x85, 0x23, 0x65, 0xa4, 0x0e, 0x25, 0xdf, 0xdb, 0x32,
	0x76, 0x8d, 0x56, 0xc5, 0x29, 0xf9, 0x1e, 0xd9, 0x83, 0xf5, 0x73, 0x1f, 0x03, 0x8f, 0x6e, 0x95,
	0x76, 0x8d, 0x56, 0xb5, 0xb3, 0x69, 0x4b, 0x4d, 0x5b, 0x6b, 0xda, 0x87, 0xd1, 0x85, 0xa3, 0x30,
	0x56, 0x1f, 0xee, 0x16, 0x34, 0x69, 0x12, 0x47, 0x14, 0x97, 0x14, 0x7d, 0x04, 0xa4, 0x8b, 0xf3,
	0x8c, 0x66, 0xad, 0x0b, 0xa8, 0xff, 0xd2, 0xfa, 0x09, 0xdc, 0x3b, 0xc6, 0x00, 0x19, 0xce, 0xeb,
	0xde, 0x82, 0xc6, 0x75, 0xe0, 0x9f, 0x0d, 0x58, 0x3f, 0x4a, 0x50, 0x3d, 0xe2, 0xc1, 0x67, 0xad,
	0xf4, 0x00, 0x60, 0xe8, 0xb2, 0xd1, 0x64, 0x40, 0xfd, 0x4b, 0x14, 0xb8, 0x35, 0xa7, 0x22, 0x2a,
	0x7d, 0xff, 0x12, 0xc9, 0x29, 0x6c, 0xf0, 0xc4, 0x73, 0x19, 0x0e, 0x52, 0x49, 0xc8, 0x8c, 0xaf,
	0xb4, 0xaa, 0x9d, 0x5d, 0x5b, 0xac, 0xdf, 0x9e, 0xd2, 0xb2, 0x3f, 0x0a, 0xa4, 0x3a, 0x39, 0x75,
	0x3e, 0x7d, 0xa4, 0xcd, 0x9f, 0x06, 0x98, 0x05, 0x04, 0x69, 0xc0, 0x7a, 0x88, 0x6c, 0x12, 0x6b,
	0x7f, 0xea, 0x44, 0x4e, 0xa0, 0xec, 0xa9, 0x39, 0x54, 0x4c, 0x4f, 0xe7, 0x75, 0xb3, 0xf3, 0xc1,
	0x73, 0x6a, 0xf3, 0x0d, 0x94, 0x75, 0x75, 0xc9, 0x3d, 0x7c, 0x37, 0xa0, 0x26, 0x5b, 0xab, 0x54,
	0x77, 0xa0, 0x92, 0x70, 0x36, 0x18, 0xc5, 0x3c, 0x62, 0x2a, 0xb4, 0x72, 0xc2, 0xd9, 0xeb, 0xec,
	0x4c, 0x1e, 0xc3, 0x46, 0x76, 0x89, 0x69, 0x1a, 0xa7, 0x0a, 0x52, 0x12, 0x10, 0x33, 0xe1, 0xec,
	0x24, 0xab, 0x4a, 0xdc, 0x43, 0xa8, 0x79, 0x62, 0x69, 0x0a, 0xb4, 0x22, 0x40, 0x55, 0x59, 0x93,
	0x90, 0x3d, 0x20, 0x32, 0x93, 0x82, 0xda, 0xaa, 0x00, 0xde, 0x96, 0x37, 0x57, 0x82, 0xd6, 0x5b,
	0x30, 0xfb, 0xe8, 0xa6, 0xa3, 0x89, 0x0e, 0xf8, 0x05, 0xd4, 0xa9, 0x28, 0xe8, 0xed, 0x09, 0xaf,
	0x7f, 0x9b, 0xd6, 0xa4, 0xd3, 0x64, 0xeb, 0x0c, 0xea, 0x5a, 0x4d, 0x4d, 0x7d, 0x00, 0x66, 0x2e,
	0x47, 0x79, 0x30, 0x5b, 0xad, 0xa6, 0xd5, 0x32, 0xa4, 0xf5, 0x0a, 0xea, 0x3d, 0xce, 0xde, 0xc7,
	0x5e, 0xbe, 0xfc, 0x2d, 0xb8, 0x35, 0x0a, 0x38, 0x65, 0x98, 0xaa, 0xb5, 0xe8, 0x23, 0x21, 0xb0,
	0x1a, 0xc5, 0x1e, 0x8a, 0xd0, 0x2a, 0x8e, 0xf8, 0xce, 0xf8, 0x5d, 0x5c, 0x82, 0xff, 0x12, 0x36,
	0x72, 0xbe, 0x9a, 0xe6, 0x19, 0xac, 0x7d, 0x75, 0x03, 0x8e, 0x33, 0xa7, 0x90, 0x10, 0xeb, 0x10,
	0xee, 0xc8, 0xff, 0xd7, 0xbf, 0x3b, 0x08, 0xa1, 0xd1, 0xe3, 0xec, 0x34, 0xf2, 0xf0, 0xdb, 0x3b,
	0x37, 0x49, 0xfc, 0x68, 0x3c, 0x5f, 0xe7, 0x00, 0x4c, 0x3f, 0x23, 0x0c, 0x42, 0xc9, 0x98, 0xf9,
	0x63, 0xad, 0xf9, 0x53, 0xda, 0x56, 0x07, 0x1a, 0x5d, 0xbc, 0x59, 0x3b, 0xeb, 0x03, 0xdc, 0xff,
	0x8d, 0x73, 0xb5, 0xfa, 0xa2, 0x13, 0x63, 0x61, 0x27, 0xcf, 0x61, 0x5b, 0x66, 0x77, 0x33, 0x33,
	0x9e, 0x78, 0xcb, 0x25, 0x07, 0x99, 0x3b, 0x3f, 0xac, 0x7d, 0x00, 0x65, 0x11, 0x99, 0x3b, 0x33,
	0xa9, 0x8a, 0xaf, 0x55, 0xad, 0xb6, 0x78, 0xb6, 0x17, 0xef, 0x62, 0x9d, 0xc1, 0x66, 0x91, 0xa0,
	0x02, 0x2a, 0x76, 0x37, 0x16, 0xeb, 0xde, 0xd1, 0xcf, 0xf6, 0xe2, 0x06, 0x8e, 0xe0, 0x53, 0x59,
	0xcb, 0x0d, 0xd7, 0xc5, 0xd7, 0xfe, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0x1a, 0x95, 0xdc,
	0xa3, 0x07, 0x00, 0x00,
}
