// Code generated by protoc-gen-go.
// source: protobuf/supervise_rpc.proto
// DO NOT EDIT!

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Cluster service

type ClusterClient interface {
	PutNode(ctx context.Context, in *PutNodeRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type clusterClient struct {
	cc *grpc.ClientConn
}

func NewClusterClient(cc *grpc.ClientConn) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) PutNode(ctx context.Context, in *PutNodeRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/blast.Cluster/PutNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	out := new(GetNodeResponse)
	err := grpc.Invoke(ctx, "/blast.Cluster/GetNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/blast.Cluster/DeleteNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cluster service

type ClusterServer interface {
	PutNode(context.Context, *PutNodeRequest) (*google_protobuf1.Empty, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	DeleteNode(context.Context, *DeleteNodeRequest) (*google_protobuf1.Empty, error)
}

func RegisterClusterServer(s *grpc.Server, srv ClusterServer) {
	s.RegisterService(&_Cluster_serviceDesc, srv)
}

func _Cluster_PutNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).PutNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blast.Cluster/PutNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).PutNode(ctx, req.(*PutNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blast.Cluster/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blast.Cluster/DeleteNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).DeleteNode(ctx, req.(*DeleteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blast.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutNode",
			Handler:    _Cluster_PutNode_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _Cluster_GetNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _Cluster_DeleteNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/supervise_rpc.proto",
}

func init() { proto.RegisterFile("protobuf/supervise_rpc.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x2e, 0x2d, 0x48, 0x2d, 0x2a, 0xcb, 0x2c, 0x4e, 0x8d, 0x2f,
	0x2a, 0x48, 0xd6, 0x03, 0x0b, 0x0b, 0xb1, 0x26, 0xe5, 0x24, 0x16, 0x97, 0x48, 0x89, 0xc1, 0x15,
	0xe5, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x42, 0xa4, 0xa5, 0xa4, 0xd3, 0xf3, 0xf3, 0xd3, 0x73,
	0x52, 0xf5, 0xe1, 0xd2, 0xa9, 0xb9, 0x05, 0x25, 0x95, 0x10, 0x49, 0xa3, 0xc3, 0x8c, 0x5c, 0xec,
	0xce, 0x39, 0xa5, 0xc5, 0x25, 0xa9, 0x45, 0x42, 0x56, 0x5c, 0xec, 0x01, 0xa5, 0x25, 0x7e, 0xf9,
	0x29, 0xa9, 0x42, 0xa2, 0x7a, 0x60, 0x33, 0xf5, 0xa0, 0xfc, 0xa0, 0xd4, 0xc2, 0xd2, 0x54, 0x90,
	0x15, 0x7a, 0x10, 0xb3, 0xf4, 0x60, 0x66, 0xe9, 0xb9, 0x82, 0xcc, 0x52, 0x62, 0x00, 0xe9, 0x75,
	0x4f, 0x45, 0xd5, 0x0b, 0xe5, 0x23, 0xf4, 0xa2, 0x09, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x2a,
	0x31, 0x08, 0x39, 0x70, 0x71, 0xb9, 0xa4, 0xe6, 0xa4, 0x96, 0xa4, 0x82, 0xb5, 0x4b, 0x40, 0xd5,
	0x21, 0x84, 0x08, 0xda, 0xee, 0xc4, 0x15, 0xc5, 0x01, 0x13, 0x4b, 0x62, 0x03, 0xb3, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x0c, 0x22, 0x6d, 0x34, 0x01, 0x00, 0x00,
}
