// Code generated by protoc-gen-go.
// source: proto/index_service.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetIndexPathResponse struct {
	IndexPath string `protobuf:"bytes,1,opt,name=index_path,json=indexPath" json:"index_path,omitempty"`
}

func (m *GetIndexPathResponse) Reset()                    { *m = GetIndexPathResponse{} }
func (m *GetIndexPathResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetIndexPathResponse) ProtoMessage()               {}
func (*GetIndexPathResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *GetIndexPathResponse) GetIndexPath() string {
	if m != nil {
		return m.IndexPath
	}
	return ""
}

type GetIndexMappingResponse struct {
	IndexMapping *google_protobuf.Any `protobuf:"bytes,1,opt,name=index_mapping,json=indexMapping" json:"index_mapping,omitempty"`
}

func (m *GetIndexMappingResponse) Reset()                    { *m = GetIndexMappingResponse{} }
func (m *GetIndexMappingResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetIndexMappingResponse) ProtoMessage()               {}
func (*GetIndexMappingResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *GetIndexMappingResponse) GetIndexMapping() *google_protobuf.Any {
	if m != nil {
		return m.IndexMapping
	}
	return nil
}

type GetIndexMetaResponse struct {
	IndexType string               `protobuf:"bytes,1,opt,name=index_type,json=indexType" json:"index_type,omitempty"`
	Storage   string               `protobuf:"bytes,2,opt,name=storage" json:"storage,omitempty"`
	Config    *google_protobuf.Any `protobuf:"bytes,3,opt,name=config" json:"config,omitempty"`
}

func (m *GetIndexMetaResponse) Reset()                    { *m = GetIndexMetaResponse{} }
func (m *GetIndexMetaResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetIndexMetaResponse) ProtoMessage()               {}
func (*GetIndexMetaResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *GetIndexMetaResponse) GetIndexType() string {
	if m != nil {
		return m.IndexType
	}
	return ""
}

func (m *GetIndexMetaResponse) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

func (m *GetIndexMetaResponse) GetConfig() *google_protobuf.Any {
	if m != nil {
		return m.Config
	}
	return nil
}

type PutDocumentRequest struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *PutDocumentRequest) Reset()                    { *m = PutDocumentRequest{} }
func (m *PutDocumentRequest) String() string            { return proto1.CompactTextString(m) }
func (*PutDocumentRequest) ProtoMessage()               {}
func (*PutDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *PutDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutDocumentRequest) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type PutDocumentResponse struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *PutDocumentResponse) Reset()                    { *m = PutDocumentResponse{} }
func (m *PutDocumentResponse) String() string            { return proto1.CompactTextString(m) }
func (*PutDocumentResponse) ProtoMessage()               {}
func (*PutDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *PutDocumentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutDocumentResponse) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type GetDocumentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetDocumentRequest) Reset()                    { *m = GetDocumentRequest{} }
func (m *GetDocumentRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetDocumentRequest) ProtoMessage()               {}
func (*GetDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *GetDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetDocumentResponse struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *GetDocumentResponse) Reset()                    { *m = GetDocumentResponse{} }
func (m *GetDocumentResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetDocumentResponse) ProtoMessage()               {}
func (*GetDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *GetDocumentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetDocumentResponse) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type DeleteDocumentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteDocumentRequest) Reset()                    { *m = DeleteDocumentRequest{} }
func (m *DeleteDocumentRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteDocumentRequest) ProtoMessage()               {}
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *DeleteDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteDocumentResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteDocumentResponse) Reset()                    { *m = DeleteDocumentResponse{} }
func (m *DeleteDocumentResponse) String() string            { return proto1.CompactTextString(m) }
func (*DeleteDocumentResponse) ProtoMessage()               {}
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *DeleteDocumentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type BulkRequest struct {
	BatchSize      int32                        `protobuf:"varint,1,opt,name=batch_size,json=batchSize" json:"batch_size,omitempty"`
	UpdateRequests []*BulkRequest_UpdateRequest `protobuf:"bytes,2,rep,name=update_requests,json=updateRequests" json:"update_requests,omitempty"`
}

func (m *BulkRequest) Reset()                    { *m = BulkRequest{} }
func (m *BulkRequest) String() string            { return proto1.CompactTextString(m) }
func (*BulkRequest) ProtoMessage()               {}
func (*BulkRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *BulkRequest) GetBatchSize() int32 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

func (m *BulkRequest) GetUpdateRequests() []*BulkRequest_UpdateRequest {
	if m != nil {
		return m.UpdateRequests
	}
	return nil
}

type BulkRequest_UpdateRequest struct {
	Method   string                              `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Document *BulkRequest_UpdateRequest_Document `protobuf:"bytes,2,opt,name=document" json:"document,omitempty"`
}

func (m *BulkRequest_UpdateRequest) Reset()                    { *m = BulkRequest_UpdateRequest{} }
func (m *BulkRequest_UpdateRequest) String() string            { return proto1.CompactTextString(m) }
func (*BulkRequest_UpdateRequest) ProtoMessage()               {}
func (*BulkRequest_UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9, 0} }

func (m *BulkRequest_UpdateRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *BulkRequest_UpdateRequest) GetDocument() *BulkRequest_UpdateRequest_Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type BulkRequest_UpdateRequest_Document struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *BulkRequest_UpdateRequest_Document) Reset()         { *m = BulkRequest_UpdateRequest_Document{} }
func (m *BulkRequest_UpdateRequest_Document) String() string { return proto1.CompactTextString(m) }
func (*BulkRequest_UpdateRequest_Document) ProtoMessage()    {}
func (*BulkRequest_UpdateRequest_Document) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{9, 0, 0}
}

func (m *BulkRequest_UpdateRequest_Document) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BulkRequest_UpdateRequest_Document) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type BulkResponse struct {
	PutCount         int32 `protobuf:"varint,1,opt,name=put_count,json=putCount" json:"put_count,omitempty"`
	PutErrorCount    int32 `protobuf:"varint,2,opt,name=put_error_count,json=putErrorCount" json:"put_error_count,omitempty"`
	DeleteCount      int32 `protobuf:"varint,3,opt,name=delete_count,json=deleteCount" json:"delete_count,omitempty"`
	MethodErrorCount int32 `protobuf:"varint,4,opt,name=method_error_count,json=methodErrorCount" json:"method_error_count,omitempty"`
}

func (m *BulkResponse) Reset()                    { *m = BulkResponse{} }
func (m *BulkResponse) String() string            { return proto1.CompactTextString(m) }
func (*BulkResponse) ProtoMessage()               {}
func (*BulkResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *BulkResponse) GetPutCount() int32 {
	if m != nil {
		return m.PutCount
	}
	return 0
}

func (m *BulkResponse) GetPutErrorCount() int32 {
	if m != nil {
		return m.PutErrorCount
	}
	return 0
}

func (m *BulkResponse) GetDeleteCount() int32 {
	if m != nil {
		return m.DeleteCount
	}
	return 0
}

func (m *BulkResponse) GetMethodErrorCount() int32 {
	if m != nil {
		return m.MethodErrorCount
	}
	return 0
}

type SearchRequest struct {
	SearchRequest *google_protobuf.Any `protobuf:"bytes,1,opt,name=search_request,json=searchRequest" json:"search_request,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto1.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *SearchRequest) GetSearchRequest() *google_protobuf.Any {
	if m != nil {
		return m.SearchRequest
	}
	return nil
}

type SearchResponse struct {
	SearchResult *google_protobuf.Any `protobuf:"bytes,1,opt,name=search_result,json=searchResult" json:"search_result,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto1.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *SearchResponse) GetSearchResult() *google_protobuf.Any {
	if m != nil {
		return m.SearchResult
	}
	return nil
}

func init() {
	proto1.RegisterType((*GetIndexPathResponse)(nil), "proto.GetIndexPathResponse")
	proto1.RegisterType((*GetIndexMappingResponse)(nil), "proto.GetIndexMappingResponse")
	proto1.RegisterType((*GetIndexMetaResponse)(nil), "proto.GetIndexMetaResponse")
	proto1.RegisterType((*PutDocumentRequest)(nil), "proto.PutDocumentRequest")
	proto1.RegisterType((*PutDocumentResponse)(nil), "proto.PutDocumentResponse")
	proto1.RegisterType((*GetDocumentRequest)(nil), "proto.GetDocumentRequest")
	proto1.RegisterType((*GetDocumentResponse)(nil), "proto.GetDocumentResponse")
	proto1.RegisterType((*DeleteDocumentRequest)(nil), "proto.DeleteDocumentRequest")
	proto1.RegisterType((*DeleteDocumentResponse)(nil), "proto.DeleteDocumentResponse")
	proto1.RegisterType((*BulkRequest)(nil), "proto.BulkRequest")
	proto1.RegisterType((*BulkRequest_UpdateRequest)(nil), "proto.BulkRequest.UpdateRequest")
	proto1.RegisterType((*BulkRequest_UpdateRequest_Document)(nil), "proto.BulkRequest.UpdateRequest.Document")
	proto1.RegisterType((*BulkResponse)(nil), "proto.BulkResponse")
	proto1.RegisterType((*SearchRequest)(nil), "proto.SearchRequest")
	proto1.RegisterType((*SearchResponse)(nil), "proto.SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Index service

type IndexClient interface {
	GetIndexPath(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetIndexPathResponse, error)
	GetIndexMapping(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetIndexMappingResponse, error)
	GetIndexMeta(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetIndexMetaResponse, error)
	//    rpc GetIndexType(google.protobuf.Empty) returns (GetIndexTypeResponse) {}
	//    rpc GetKvstore(google.protobuf.Empty) returns (GetKvstoreResponse) {}
	//    rpc GetKvconfig(google.protobuf.Empty) returns (GetKvconfigResponse) {}
	PutDocument(ctx context.Context, in *PutDocumentRequest, opts ...grpc.CallOption) (*PutDocumentResponse, error)
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error)
	Bulk(ctx context.Context, in *BulkRequest, opts ...grpc.CallOption) (*BulkResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type indexClient struct {
	cc *grpc.ClientConn
}

func NewIndexClient(cc *grpc.ClientConn) IndexClient {
	return &indexClient{cc}
}

func (c *indexClient) GetIndexPath(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetIndexPathResponse, error) {
	out := new(GetIndexPathResponse)
	err := grpc.Invoke(ctx, "/proto.Index/GetIndexPath", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) GetIndexMapping(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetIndexMappingResponse, error) {
	out := new(GetIndexMappingResponse)
	err := grpc.Invoke(ctx, "/proto.Index/GetIndexMapping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) GetIndexMeta(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetIndexMetaResponse, error) {
	out := new(GetIndexMetaResponse)
	err := grpc.Invoke(ctx, "/proto.Index/GetIndexMeta", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) PutDocument(ctx context.Context, in *PutDocumentRequest, opts ...grpc.CallOption) (*PutDocumentResponse, error) {
	out := new(PutDocumentResponse)
	err := grpc.Invoke(ctx, "/proto.Index/PutDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	out := new(GetDocumentResponse)
	err := grpc.Invoke(ctx, "/proto.Index/GetDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error) {
	out := new(DeleteDocumentResponse)
	err := grpc.Invoke(ctx, "/proto.Index/DeleteDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) Bulk(ctx context.Context, in *BulkRequest, opts ...grpc.CallOption) (*BulkResponse, error) {
	out := new(BulkResponse)
	err := grpc.Invoke(ctx, "/proto.Index/Bulk", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/proto.Index/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Index service

type IndexServer interface {
	GetIndexPath(context.Context, *google_protobuf1.Empty) (*GetIndexPathResponse, error)
	GetIndexMapping(context.Context, *google_protobuf1.Empty) (*GetIndexMappingResponse, error)
	GetIndexMeta(context.Context, *google_protobuf1.Empty) (*GetIndexMetaResponse, error)
	//    rpc GetIndexType(google.protobuf.Empty) returns (GetIndexTypeResponse) {}
	//    rpc GetKvstore(google.protobuf.Empty) returns (GetKvstoreResponse) {}
	//    rpc GetKvconfig(google.protobuf.Empty) returns (GetKvconfigResponse) {}
	PutDocument(context.Context, *PutDocumentRequest) (*PutDocumentResponse, error)
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error)
	Bulk(context.Context, *BulkRequest) (*BulkResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterIndexServer(s *grpc.Server, srv IndexServer) {
	s.RegisterService(&_Index_serviceDesc, srv)
}

func _Index_GetIndexPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetIndexPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Index/GetIndexPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetIndexPath(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_GetIndexMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetIndexMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Index/GetIndexMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetIndexMapping(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_GetIndexMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetIndexMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Index/GetIndexMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetIndexMeta(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_PutDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).PutDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Index/PutDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).PutDocument(ctx, req.(*PutDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Index/GetDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Index/DeleteDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_Bulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).Bulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Index/Bulk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).Bulk(ctx, req.(*BulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Index/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Index_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Index",
	HandlerType: (*IndexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIndexPath",
			Handler:    _Index_GetIndexPath_Handler,
		},
		{
			MethodName: "GetIndexMapping",
			Handler:    _Index_GetIndexMapping_Handler,
		},
		{
			MethodName: "GetIndexMeta",
			Handler:    _Index_GetIndexMeta_Handler,
		},
		{
			MethodName: "PutDocument",
			Handler:    _Index_PutDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _Index_GetDocument_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _Index_DeleteDocument_Handler,
		},
		{
			MethodName: "Bulk",
			Handler:    _Index_Bulk_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Index_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/index_service.proto",
}

func init() { proto1.RegisterFile("proto/index_service.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x4f, 0x13, 0x41,
	0x14, 0x6d, 0x0b, 0x54, 0x7a, 0xfb, 0x81, 0x19, 0x3e, 0x2c, 0x8b, 0x18, 0x9c, 0x18, 0xc5, 0x84,
	0x2c, 0x11, 0x63, 0x8c, 0xf1, 0x49, 0xa5, 0x22, 0x41, 0x22, 0x59, 0xf0, 0xb9, 0x59, 0xba, 0x97,
	0x76, 0x63, 0xbb, 0x3b, 0xee, 0xce, 0x18, 0x4b, 0xe2, 0xbf, 0xf1, 0xdd, 0xc4, 0x27, 0x7f, 0x9e,
	0xd9, 0xf9, 0x58, 0x76, 0xb7, 0x85, 0x9a, 0xe0, 0x53, 0x73, 0xef, 0x3d, 0xe7, 0xdc, 0x33, 0x33,
	0xdd, 0x03, 0xeb, 0x2c, 0x0a, 0x79, 0xb8, 0xeb, 0x07, 0x1e, 0x7e, 0xef, 0xc6, 0x18, 0x7d, 0xf3,
	0x7b, 0x68, 0xcb, 0x1e, 0x59, 0x90, 0x3f, 0xd6, 0x7a, 0x3f, 0x0c, 0xfb, 0x43, 0xdc, 0x95, 0xd5,
	0xb9, 0xb8, 0xd8, 0x75, 0x83, 0xb1, 0x42, 0x58, 0x1b, 0xc5, 0x11, 0x8e, 0x18, 0xd7, 0x43, 0xfa,
	0x02, 0x56, 0x0e, 0x90, 0x1f, 0x26, 0xc2, 0x27, 0x2e, 0x1f, 0x38, 0x18, 0xb3, 0x30, 0x88, 0x91,
	0x6c, 0x02, 0xa8, 0x6d, 0xcc, 0xe5, 0x83, 0x76, 0x79, 0xab, 0xbc, 0x5d, 0x73, 0x6a, 0xbe, 0x81,
	0xd1, 0x33, 0xb8, 0x67, 0x68, 0xc7, 0x2e, 0x63, 0x7e, 0xd0, 0x4f, 0x99, 0xaf, 0xa0, 0xa9, 0x98,
	0x23, 0x35, 0x90, 0xe4, 0xfa, 0xde, 0x8a, 0xad, 0x6c, 0xd8, 0xc6, 0x86, 0xfd, 0x26, 0x18, 0x3b,
	0x0d, 0x3f, 0x23, 0x41, 0x7f, 0x5c, 0x99, 0x39, 0x46, 0xee, 0x4e, 0x9a, 0xe1, 0x63, 0x86, 0x39,
	0x33, 0x67, 0x63, 0x86, 0xa4, 0x0d, 0x77, 0x62, 0x1e, 0x46, 0x6e, 0x1f, 0xdb, 0x15, 0x39, 0x33,
	0x25, 0xd9, 0x81, 0x6a, 0x2f, 0x0c, 0x2e, 0xfc, 0x7e, 0x7b, 0xee, 0x06, 0x13, 0x1a, 0x43, 0x1d,
	0x20, 0x27, 0x82, 0xef, 0x87, 0x3d, 0x31, 0xc2, 0x80, 0x3b, 0xf8, 0x55, 0x60, 0xcc, 0x49, 0x0b,
	0x2a, 0xbe, 0xa7, 0x97, 0x56, 0x7c, 0x2f, 0xd1, 0xbc, 0xf0, 0x71, 0xe8, 0xc5, 0x72, 0xd9, 0xb5,
	0x9a, 0x0a, 0x43, 0x4f, 0x61, 0x39, 0xa7, 0xa9, 0x4f, 0x74, 0x3b, 0xd1, 0x47, 0x40, 0x0e, 0x70,
	0x96, 0xd1, 0x64, 0x75, 0x0e, 0xf5, 0x5f, 0x56, 0x3f, 0x81, 0xd5, 0x7d, 0x1c, 0x22, 0xc7, 0x59,
	0xdb, 0xb7, 0x61, 0xad, 0x08, 0x9c, 0x6e, 0x80, 0xfe, 0xae, 0x40, 0xfd, 0xad, 0x18, 0x7e, 0x31,
	0x4a, 0x9b, 0x00, 0xe7, 0x2e, 0xef, 0x0d, 0xba, 0xb1, 0x7f, 0xa9, 0x5e, 0x7b, 0xc1, 0xa9, 0xc9,
	0xce, 0xa9, 0x7f, 0x89, 0xe4, 0x10, 0x96, 0x04, 0xf3, 0x5c, 0x8e, 0xdd, 0x48, 0x11, 0x12, 0xe3,
	0x73, 0xdb, 0xf5, 0xbd, 0x2d, 0xe5, 0xd8, 0xce, 0x68, 0xd9, 0x9f, 0x25, 0x52, 0x57, 0x4e, 0x4b,
	0x64, 0xcb, 0xd8, 0xfa, 0x53, 0x86, 0x66, 0x0e, 0x41, 0xd6, 0xa0, 0x3a, 0x42, 0x3e, 0x08, 0x8d,
	0x3f, 0x5d, 0x91, 0x0e, 0x2c, 0x7a, 0xfa, 0x1c, 0xfa, 0x9a, 0x9e, 0xce, 0xda, 0x66, 0xa7, 0x07,
	0x4f, 0xa9, 0xd6, 0x07, 0x58, 0x34, 0xdd, 0x5b, 0xbe, 0xc3, 0xcf, 0x32, 0x34, 0xd4, 0x6a, 0x7d,
	0xab, 0x1b, 0x50, 0x63, 0x82, 0x77, 0x7b, 0xa1, 0x08, 0xb8, 0xbe, 0xb4, 0x45, 0x26, 0xf8, 0xbb,
	0xa4, 0x26, 0x8f, 0x61, 0x29, 0x19, 0x62, 0x14, 0x85, 0x91, 0x86, 0x54, 0x24, 0xa4, 0xc9, 0x04,
	0xef, 0x24, 0x5d, 0x85, 0x7b, 0x08, 0x0d, 0x4f, 0x3e, 0x9a, 0x06, 0xcd, 0x49, 0x50, 0x5d, 0xf5,
	0x14, 0x64, 0x07, 0x88, 0xba, 0x93, 0x9c, 0xda, 0xbc, 0x04, 0xde, 0x55, 0x93, 0x2b, 0x41, 0xfa,
	0x11, 0x9a, 0xa7, 0xe8, 0x46, 0xbd, 0x81, 0xb9, 0xe0, 0xd7, 0xd0, 0x8a, 0x65, 0xc3, 0xbc, 0xde,
	0x8d, 0xf1, 0xd0, 0x8c, 0xb3, 0x64, 0x7a, 0x04, 0x2d, 0xa3, 0x76, 0x15, 0x36, 0xa9, 0x5c, 0x2c,
	0x86, 0x37, 0xab, 0x35, 0x8c, 0x5a, 0x82, 0xdc, 0xfb, 0x35, 0x0f, 0x0b, 0x32, 0x6a, 0x48, 0x07,
	0x1a, 0xd9, 0x0c, 0x24, 0x6b, 0x13, 0xec, 0x4e, 0x92, 0x98, 0xd6, 0x86, 0x7e, 0xf2, 0x69, 0x81,
	0x49, 0x4b, 0xe4, 0x08, 0x96, 0x0a, 0x99, 0x78, 0xad, 0xd2, 0x83, 0x82, 0x52, 0x21, 0x43, 0x69,
	0x29, 0xeb, 0x29, 0x89, 0xc2, 0x7f, 0xf6, 0x94, 0xcd, 0x4d, 0x5a, 0x22, 0xef, 0xa1, 0x9e, 0x89,
	0x1f, 0xb2, 0xae, 0xd1, 0x93, 0x31, 0x67, 0x59, 0xd3, 0x46, 0x59, 0x9d, 0x4c, 0x96, 0xa4, 0x3a,
	0x93, 0x29, 0x94, 0xea, 0x4c, 0x89, 0x1e, 0x5a, 0x22, 0x9f, 0xa0, 0x95, 0x4f, 0x05, 0x72, 0x5f,
	0xe3, 0xa7, 0xa6, 0x8a, 0xb5, 0x79, 0xcd, 0x34, 0x15, 0x7c, 0x06, 0xf3, 0xc9, 0x67, 0x40, 0xc8,
	0xe4, 0xe7, 0x68, 0x2d, 0xe7, 0x7a, 0x29, 0xe5, 0x25, 0x54, 0xd5, 0xbf, 0x88, 0xac, 0x68, 0x40,
	0xee, 0x2f, 0x6a, 0xad, 0x16, 0xba, 0x86, 0x78, 0x5e, 0x95, 0xfd, 0xe7, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xf1, 0xa7, 0xb2, 0xe1, 0x8e, 0x07, 0x00, 0x00,
}
