// Code generated by protoc-gen-go.
// source: pb/index_service.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/index_service.proto
	pb/supervise_service.proto

It has these top-level messages:
	GetIndexPathResponse
	GetIndexMappingResponse
	GetIndexMetaResponse
	PutDocumentRequest
	PutDocumentResponse
	GetDocumentRequest
	GetDocumentResponse
	DeleteDocumentRequest
	DeleteDocumentResponse
	BulkRequest
	BulkResponse
	SearchRequest
	SearchResponse
	PutNodeRequest
	GetNodeRequest
	GetNodeResponse
	DeleteNodeRequest
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetIndexPathResponse struct {
	IndexPath string `protobuf:"bytes,1,opt,name=index_path,json=indexPath" json:"index_path,omitempty"`
}

func (m *GetIndexPathResponse) Reset()                    { *m = GetIndexPathResponse{} }
func (m *GetIndexPathResponse) String() string            { return proto.CompactTextString(m) }
func (*GetIndexPathResponse) ProtoMessage()               {}
func (*GetIndexPathResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetIndexPathResponse) GetIndexPath() string {
	if m != nil {
		return m.IndexPath
	}
	return ""
}

type GetIndexMappingResponse struct {
	IndexMapping *google_protobuf.Any `protobuf:"bytes,1,opt,name=index_mapping,json=indexMapping" json:"index_mapping,omitempty"`
}

func (m *GetIndexMappingResponse) Reset()                    { *m = GetIndexMappingResponse{} }
func (m *GetIndexMappingResponse) String() string            { return proto.CompactTextString(m) }
func (*GetIndexMappingResponse) ProtoMessage()               {}
func (*GetIndexMappingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetIndexMappingResponse) GetIndexMapping() *google_protobuf.Any {
	if m != nil {
		return m.IndexMapping
	}
	return nil
}

type GetIndexMetaResponse struct {
	IndexType string               `protobuf:"bytes,1,opt,name=index_type,json=indexType" json:"index_type,omitempty"`
	Storage   string               `protobuf:"bytes,2,opt,name=storage" json:"storage,omitempty"`
	Config    *google_protobuf.Any `protobuf:"bytes,3,opt,name=config" json:"config,omitempty"`
}

func (m *GetIndexMetaResponse) Reset()                    { *m = GetIndexMetaResponse{} }
func (m *GetIndexMetaResponse) String() string            { return proto.CompactTextString(m) }
func (*GetIndexMetaResponse) ProtoMessage()               {}
func (*GetIndexMetaResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetIndexMetaResponse) GetIndexType() string {
	if m != nil {
		return m.IndexType
	}
	return ""
}

func (m *GetIndexMetaResponse) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

func (m *GetIndexMetaResponse) GetConfig() *google_protobuf.Any {
	if m != nil {
		return m.Config
	}
	return nil
}

type PutDocumentRequest struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *PutDocumentRequest) Reset()                    { *m = PutDocumentRequest{} }
func (m *PutDocumentRequest) String() string            { return proto.CompactTextString(m) }
func (*PutDocumentRequest) ProtoMessage()               {}
func (*PutDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PutDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutDocumentRequest) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type PutDocumentResponse struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *PutDocumentResponse) Reset()                    { *m = PutDocumentResponse{} }
func (m *PutDocumentResponse) String() string            { return proto.CompactTextString(m) }
func (*PutDocumentResponse) ProtoMessage()               {}
func (*PutDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PutDocumentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutDocumentResponse) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type GetDocumentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetDocumentRequest) Reset()                    { *m = GetDocumentRequest{} }
func (m *GetDocumentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDocumentRequest) ProtoMessage()               {}
func (*GetDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetDocumentResponse struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *GetDocumentResponse) Reset()                    { *m = GetDocumentResponse{} }
func (m *GetDocumentResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDocumentResponse) ProtoMessage()               {}
func (*GetDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetDocumentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetDocumentResponse) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type DeleteDocumentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteDocumentRequest) Reset()                    { *m = DeleteDocumentRequest{} }
func (m *DeleteDocumentRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDocumentRequest) ProtoMessage()               {}
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeleteDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteDocumentResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteDocumentResponse) Reset()                    { *m = DeleteDocumentResponse{} }
func (m *DeleteDocumentResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteDocumentResponse) ProtoMessage()               {}
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeleteDocumentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type BulkRequest struct {
	BatchSize      int32                        `protobuf:"varint,1,opt,name=batch_size,json=batchSize" json:"batch_size,omitempty"`
	UpdateRequests []*BulkRequest_UpdateRequest `protobuf:"bytes,2,rep,name=update_requests,json=updateRequests" json:"update_requests,omitempty"`
}

func (m *BulkRequest) Reset()                    { *m = BulkRequest{} }
func (m *BulkRequest) String() string            { return proto.CompactTextString(m) }
func (*BulkRequest) ProtoMessage()               {}
func (*BulkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *BulkRequest) GetBatchSize() int32 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

func (m *BulkRequest) GetUpdateRequests() []*BulkRequest_UpdateRequest {
	if m != nil {
		return m.UpdateRequests
	}
	return nil
}

type BulkRequest_UpdateRequest struct {
	Method   string                              `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Document *BulkRequest_UpdateRequest_Document `protobuf:"bytes,2,opt,name=document" json:"document,omitempty"`
}

func (m *BulkRequest_UpdateRequest) Reset()                    { *m = BulkRequest_UpdateRequest{} }
func (m *BulkRequest_UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*BulkRequest_UpdateRequest) ProtoMessage()               {}
func (*BulkRequest_UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

func (m *BulkRequest_UpdateRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *BulkRequest_UpdateRequest) GetDocument() *BulkRequest_UpdateRequest_Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type BulkRequest_UpdateRequest_Document struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *BulkRequest_UpdateRequest_Document) Reset()         { *m = BulkRequest_UpdateRequest_Document{} }
func (m *BulkRequest_UpdateRequest_Document) String() string { return proto.CompactTextString(m) }
func (*BulkRequest_UpdateRequest_Document) ProtoMessage()    {}
func (*BulkRequest_UpdateRequest_Document) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 0, 0}
}

func (m *BulkRequest_UpdateRequest_Document) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BulkRequest_UpdateRequest_Document) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type BulkResponse struct {
	PutCount         int32 `protobuf:"varint,1,opt,name=put_count,json=putCount" json:"put_count,omitempty"`
	PutErrorCount    int32 `protobuf:"varint,2,opt,name=put_error_count,json=putErrorCount" json:"put_error_count,omitempty"`
	DeleteCount      int32 `protobuf:"varint,3,opt,name=delete_count,json=deleteCount" json:"delete_count,omitempty"`
	MethodErrorCount int32 `protobuf:"varint,4,opt,name=method_error_count,json=methodErrorCount" json:"method_error_count,omitempty"`
}

func (m *BulkResponse) Reset()                    { *m = BulkResponse{} }
func (m *BulkResponse) String() string            { return proto.CompactTextString(m) }
func (*BulkResponse) ProtoMessage()               {}
func (*BulkResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *BulkResponse) GetPutCount() int32 {
	if m != nil {
		return m.PutCount
	}
	return 0
}

func (m *BulkResponse) GetPutErrorCount() int32 {
	if m != nil {
		return m.PutErrorCount
	}
	return 0
}

func (m *BulkResponse) GetDeleteCount() int32 {
	if m != nil {
		return m.DeleteCount
	}
	return 0
}

func (m *BulkResponse) GetMethodErrorCount() int32 {
	if m != nil {
		return m.MethodErrorCount
	}
	return 0
}

type SearchRequest struct {
	SearchRequest *google_protobuf.Any `protobuf:"bytes,1,opt,name=search_request,json=searchRequest" json:"search_request,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SearchRequest) GetSearchRequest() *google_protobuf.Any {
	if m != nil {
		return m.SearchRequest
	}
	return nil
}

type SearchResponse struct {
	SearchResult *google_protobuf.Any `protobuf:"bytes,1,opt,name=search_result,json=searchResult" json:"search_result,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *SearchResponse) GetSearchResult() *google_protobuf.Any {
	if m != nil {
		return m.SearchResult
	}
	return nil
}

func init() {
	proto.RegisterType((*GetIndexPathResponse)(nil), "pb.GetIndexPathResponse")
	proto.RegisterType((*GetIndexMappingResponse)(nil), "pb.GetIndexMappingResponse")
	proto.RegisterType((*GetIndexMetaResponse)(nil), "pb.GetIndexMetaResponse")
	proto.RegisterType((*PutDocumentRequest)(nil), "pb.PutDocumentRequest")
	proto.RegisterType((*PutDocumentResponse)(nil), "pb.PutDocumentResponse")
	proto.RegisterType((*GetDocumentRequest)(nil), "pb.GetDocumentRequest")
	proto.RegisterType((*GetDocumentResponse)(nil), "pb.GetDocumentResponse")
	proto.RegisterType((*DeleteDocumentRequest)(nil), "pb.DeleteDocumentRequest")
	proto.RegisterType((*DeleteDocumentResponse)(nil), "pb.DeleteDocumentResponse")
	proto.RegisterType((*BulkRequest)(nil), "pb.BulkRequest")
	proto.RegisterType((*BulkRequest_UpdateRequest)(nil), "pb.BulkRequest.UpdateRequest")
	proto.RegisterType((*BulkRequest_UpdateRequest_Document)(nil), "pb.BulkRequest.UpdateRequest.Document")
	proto.RegisterType((*BulkResponse)(nil), "pb.BulkResponse")
	proto.RegisterType((*SearchRequest)(nil), "pb.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "pb.SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Index service

type IndexClient interface {
	GetIndexPath(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetIndexPathResponse, error)
	GetIndexMapping(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetIndexMappingResponse, error)
	GetIndexMeta(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetIndexMetaResponse, error)
	PutDocument(ctx context.Context, in *PutDocumentRequest, opts ...grpc.CallOption) (*PutDocumentResponse, error)
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error)
	Bulk(ctx context.Context, in *BulkRequest, opts ...grpc.CallOption) (*BulkResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type indexClient struct {
	cc *grpc.ClientConn
}

func NewIndexClient(cc *grpc.ClientConn) IndexClient {
	return &indexClient{cc}
}

func (c *indexClient) GetIndexPath(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetIndexPathResponse, error) {
	out := new(GetIndexPathResponse)
	err := grpc.Invoke(ctx, "/pb.Index/GetIndexPath", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) GetIndexMapping(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetIndexMappingResponse, error) {
	out := new(GetIndexMappingResponse)
	err := grpc.Invoke(ctx, "/pb.Index/GetIndexMapping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) GetIndexMeta(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*GetIndexMetaResponse, error) {
	out := new(GetIndexMetaResponse)
	err := grpc.Invoke(ctx, "/pb.Index/GetIndexMeta", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) PutDocument(ctx context.Context, in *PutDocumentRequest, opts ...grpc.CallOption) (*PutDocumentResponse, error) {
	out := new(PutDocumentResponse)
	err := grpc.Invoke(ctx, "/pb.Index/PutDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	out := new(GetDocumentResponse)
	err := grpc.Invoke(ctx, "/pb.Index/GetDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error) {
	out := new(DeleteDocumentResponse)
	err := grpc.Invoke(ctx, "/pb.Index/DeleteDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) Bulk(ctx context.Context, in *BulkRequest, opts ...grpc.CallOption) (*BulkResponse, error) {
	out := new(BulkResponse)
	err := grpc.Invoke(ctx, "/pb.Index/Bulk", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/pb.Index/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Index service

type IndexServer interface {
	GetIndexPath(context.Context, *google_protobuf1.Empty) (*GetIndexPathResponse, error)
	GetIndexMapping(context.Context, *google_protobuf1.Empty) (*GetIndexMappingResponse, error)
	GetIndexMeta(context.Context, *google_protobuf1.Empty) (*GetIndexMetaResponse, error)
	PutDocument(context.Context, *PutDocumentRequest) (*PutDocumentResponse, error)
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error)
	Bulk(context.Context, *BulkRequest) (*BulkResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterIndexServer(s *grpc.Server, srv IndexServer) {
	s.RegisterService(&_Index_serviceDesc, srv)
}

func _Index_GetIndexPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetIndexPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Index/GetIndexPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetIndexPath(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_GetIndexMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetIndexMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Index/GetIndexMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetIndexMapping(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_GetIndexMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetIndexMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Index/GetIndexMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetIndexMeta(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_PutDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).PutDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Index/PutDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).PutDocument(ctx, req.(*PutDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Index/GetDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Index/DeleteDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_Bulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).Bulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Index/Bulk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).Bulk(ctx, req.(*BulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Index/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Index_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Index",
	HandlerType: (*IndexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIndexPath",
			Handler:    _Index_GetIndexPath_Handler,
		},
		{
			MethodName: "GetIndexMapping",
			Handler:    _Index_GetIndexMapping_Handler,
		},
		{
			MethodName: "GetIndexMeta",
			Handler:    _Index_GetIndexMeta_Handler,
		},
		{
			MethodName: "PutDocument",
			Handler:    _Index_PutDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _Index_GetDocument_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _Index_DeleteDocument_Handler,
		},
		{
			MethodName: "Bulk",
			Handler:    _Index_Bulk_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Index_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/index_service.proto",
}

func init() { proto.RegisterFile("pb/index_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0x5f, 0x4f, 0x13, 0x5f,
	0x10, 0x6d, 0x0b, 0xf4, 0x47, 0xa7, 0xff, 0xf8, 0x5d, 0xb1, 0x94, 0x25, 0x24, 0xba, 0x31, 0x48,
	0x22, 0x59, 0x22, 0xc6, 0x07, 0xe3, 0x8b, 0x22, 0x08, 0x44, 0x49, 0xc8, 0x82, 0xcf, 0xcd, 0xb6,
	0x3b, 0xb4, 0x1b, 0xdb, 0xdd, 0xeb, 0xee, 0x5d, 0x63, 0x49, 0x7c, 0xf7, 0x83, 0xf8, 0xe8, 0xab,
	0xdf, 0xcf, 0xdc, 0x7f, 0xdb, 0xbb, 0x6d, 0x29, 0x26, 0xf8, 0x38, 0x33, 0x67, 0xce, 0x9c, 0x9d,
	0xb9, 0x7b, 0xa0, 0x45, 0xbb, 0xfb, 0x41, 0xe8, 0xe3, 0xb7, 0x4e, 0x82, 0xf1, 0xd7, 0xa0, 0x87,
	0x0e, 0x8d, 0x23, 0x16, 0x91, 0x12, 0xed, 0x5a, 0x9b, 0xfd, 0x28, 0xea, 0x0f, 0x71, 0x5f, 0x64,
	0xba, 0xe9, 0xf5, 0xbe, 0x17, 0x8e, 0x65, 0xd9, 0xda, 0x9a, 0x2e, 0xe1, 0x88, 0x32, 0x55, 0xb4,
	0x5f, 0xc2, 0xfa, 0x09, 0xb2, 0x33, 0xce, 0x7a, 0xe1, 0xb1, 0x81, 0x8b, 0x09, 0x8d, 0xc2, 0x04,
	0xc9, 0x36, 0x80, 0x1c, 0x45, 0x3d, 0x36, 0x68, 0x17, 0x1f, 0x15, 0x77, 0x2b, 0x6e, 0x25, 0xd0,
	0x30, 0xfb, 0x0a, 0x36, 0x74, 0xdb, 0xb9, 0x47, 0x69, 0x10, 0xf6, 0xb3, 0xce, 0x57, 0x50, 0x97,
	0x9d, 0x23, 0x59, 0x10, 0xcd, 0xd5, 0x83, 0x75, 0x47, 0xca, 0x70, 0xb4, 0x0c, 0xe7, 0x6d, 0x38,
	0x76, 0x6b, 0x81, 0x41, 0x61, 0x7f, 0x9f, 0x88, 0x39, 0x47, 0xe6, 0xcd, 0x8a, 0x61, 0x63, 0x8a,
	0x39, 0x31, 0x57, 0x63, 0x8a, 0xa4, 0x0d, 0xff, 0x25, 0x2c, 0x8a, 0xbd, 0x3e, 0xb6, 0x4b, 0xa2,
	0xa6, 0x43, 0xb2, 0x07, 0xe5, 0x5e, 0x14, 0x5e, 0x07, 0xfd, 0xf6, 0xd2, 0x02, 0x11, 0x0a, 0x63,
	0xbb, 0x40, 0x2e, 0x52, 0x76, 0x14, 0xf5, 0xd2, 0x11, 0x86, 0xcc, 0xc5, 0x2f, 0x29, 0x26, 0x8c,
	0x34, 0xa0, 0x14, 0xf8, 0x6a, 0x68, 0x29, 0xf0, 0x39, 0xe7, 0x75, 0x80, 0x43, 0x3f, 0x11, 0xc3,
	0x6e, 0xe5, 0x94, 0x18, 0xfb, 0x12, 0x1e, 0xe4, 0x38, 0xd5, 0x17, 0xdd, 0x8f, 0xf4, 0x09, 0x90,
	0x13, 0xbc, 0x4b, 0x28, 0x1f, 0x9d, 0x43, 0xfd, 0x93, 0xd1, 0x4f, 0xe1, 0xe1, 0x11, 0x0e, 0x91,
	0xe1, 0x5d, 0xd3, 0x77, 0xa1, 0x35, 0x0d, 0x9c, 0x2f, 0xc0, 0xfe, 0x55, 0x82, 0xea, 0x61, 0x3a,
	0xfc, 0xac, 0x99, 0xb6, 0x01, 0xba, 0x1e, 0xeb, 0x0d, 0x3a, 0x49, 0x70, 0x23, 0xaf, 0xbd, 0xe2,
	0x56, 0x44, 0xe6, 0x32, 0xb8, 0x41, 0xf2, 0x1e, 0x9a, 0x29, 0xf5, 0x3d, 0x86, 0x9d, 0x58, 0x36,
	0x70, 0xe1, 0x4b, 0xbb, 0xd5, 0x83, 0x6d, 0x87, 0x76, 0x1d, 0x83, 0xc8, 0xf9, 0x24, 0x60, 0x2a,
	0x72, 0x1b, 0xa9, 0x19, 0x26, 0xd6, 0xef, 0x22, 0xd4, 0x73, 0x08, 0xd2, 0x82, 0xf2, 0x08, 0xd9,
	0x20, 0xd2, 0xe2, 0x54, 0x44, 0x0e, 0x61, 0xd5, 0x57, 0x1f, 0xa1, 0x76, 0xb4, 0xb3, 0x70, 0x94,
	0x93, 0x7d, 0x72, 0xd6, 0x67, 0x9d, 0xc2, 0xaa, 0xce, 0xde, 0xf3, 0x02, 0x3f, 0x8b, 0x50, 0x93,
	0xa3, 0xd5, 0x3e, 0xb7, 0xa0, 0x42, 0x53, 0xd6, 0xe9, 0x45, 0x69, 0xc8, 0xd4, 0xba, 0x56, 0x69,
	0xca, 0xde, 0xf1, 0x98, 0xec, 0x40, 0x93, 0x17, 0x31, 0x8e, 0xa3, 0x58, 0x41, 0x4a, 0x02, 0x52,
	0xa7, 0x29, 0x3b, 0xe6, 0x59, 0x89, 0x7b, 0x0c, 0x35, 0x5f, 0x9c, 0x4b, 0x81, 0x96, 0x04, 0xa8,
	0x2a, 0x73, 0x12, 0xb2, 0x07, 0x44, 0x2e, 0x24, 0xc7, 0xb6, 0x2c, 0x80, 0x6b, 0xb2, 0x32, 0x21,
	0xb4, 0x3f, 0x42, 0xfd, 0x12, 0xbd, 0xb8, 0x37, 0xd0, 0xdb, 0x7d, 0x0d, 0x8d, 0x44, 0x24, 0xf4,
	0xdd, 0x16, 0x1a, 0x43, 0x3d, 0x31, 0x9b, 0xed, 0x0f, 0xd0, 0xd0, 0x6c, 0x13, 0x9b, 0xc9, 0xe8,
	0x92, 0x74, 0xb8, 0x98, 0xad, 0xa6, 0xd9, 0x38, 0xf2, 0xe0, 0xc7, 0x32, 0xac, 0x08, 0x93, 0x21,
	0x87, 0x50, 0x33, 0xdd, 0x8f, 0xb4, 0x66, 0xba, 0x8f, 0xb9, 0x57, 0x5a, 0x6d, 0x7e, 0xef, 0x79,
	0x3e, 0x69, 0x17, 0xc8, 0x29, 0x34, 0xa7, 0xac, 0xf0, 0x56, 0x9a, 0x2d, 0x93, 0x66, 0xca, 0x37,
	0xed, 0x82, 0xa9, 0x86, 0xdb, 0xdf, 0xdf, 0xa9, 0x31, 0x8d, 0xd2, 0x2e, 0x90, 0x37, 0x50, 0x35,
	0xfc, 0x86, 0xb4, 0x38, 0x74, 0xd6, 0xd4, 0xac, 0x8d, 0x99, 0xbc, 0xc9, 0x60, 0xd8, 0x86, 0x64,
	0x98, 0x75, 0x1b, 0xc9, 0x30, 0xc7, 0x5f, 0xec, 0x02, 0x39, 0x83, 0x46, 0xfe, 0xd7, 0x27, 0x9b,
	0x1c, 0x3c, 0xd7, 0x37, 0x2c, 0x6b, 0x5e, 0x29, 0xa3, 0x7a, 0x06, 0xcb, 0xfc, 0xad, 0x93, 0xe6,
	0xd4, 0x0f, 0x67, 0xad, 0x4d, 0x12, 0x19, 0xf8, 0x39, 0x94, 0xe5, 0x23, 0x21, 0xff, 0xf3, 0x6a,
	0xee, 0xf9, 0x59, 0xc4, 0x4c, 0xe9, 0x96, 0x6e, 0x59, 0xac, 0xf6, 0xc5, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x3e, 0x6a, 0x72, 0xa9, 0x5b, 0x07, 0x00, 0x00,
}
