// Code generated by protoc-gen-go.
// source: pb/message.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"
import _ "github.com/golang/protobuf/ptypes/empty"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetIndexPathResponse struct {
	IndexPath string `protobuf:"bytes,1,opt,name=index_path,json=indexPath" json:"index_path,omitempty"`
}

func (m *GetIndexPathResponse) Reset()                    { *m = GetIndexPathResponse{} }
func (m *GetIndexPathResponse) String() string            { return proto.CompactTextString(m) }
func (*GetIndexPathResponse) ProtoMessage()               {}
func (*GetIndexPathResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *GetIndexPathResponse) GetIndexPath() string {
	if m != nil {
		return m.IndexPath
	}
	return ""
}

type GetIndexMappingResponse struct {
	IndexMapping *google_protobuf.Any `protobuf:"bytes,1,opt,name=index_mapping,json=indexMapping" json:"index_mapping,omitempty"`
}

func (m *GetIndexMappingResponse) Reset()                    { *m = GetIndexMappingResponse{} }
func (m *GetIndexMappingResponse) String() string            { return proto.CompactTextString(m) }
func (*GetIndexMappingResponse) ProtoMessage()               {}
func (*GetIndexMappingResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *GetIndexMappingResponse) GetIndexMapping() *google_protobuf.Any {
	if m != nil {
		return m.IndexMapping
	}
	return nil
}

type GetIndexMetaResponse struct {
	IndexType string               `protobuf:"bytes,1,opt,name=index_type,json=indexType" json:"index_type,omitempty"`
	Storage   string               `protobuf:"bytes,2,opt,name=storage" json:"storage,omitempty"`
	Config    *google_protobuf.Any `protobuf:"bytes,3,opt,name=config" json:"config,omitempty"`
}

func (m *GetIndexMetaResponse) Reset()                    { *m = GetIndexMetaResponse{} }
func (m *GetIndexMetaResponse) String() string            { return proto.CompactTextString(m) }
func (*GetIndexMetaResponse) ProtoMessage()               {}
func (*GetIndexMetaResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *GetIndexMetaResponse) GetIndexType() string {
	if m != nil {
		return m.IndexType
	}
	return ""
}

func (m *GetIndexMetaResponse) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

func (m *GetIndexMetaResponse) GetConfig() *google_protobuf.Any {
	if m != nil {
		return m.Config
	}
	return nil
}

type PutDocumentRequest struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *PutDocumentRequest) Reset()                    { *m = PutDocumentRequest{} }
func (m *PutDocumentRequest) String() string            { return proto.CompactTextString(m) }
func (*PutDocumentRequest) ProtoMessage()               {}
func (*PutDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *PutDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutDocumentRequest) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type PutDocumentResponse struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *PutDocumentResponse) Reset()                    { *m = PutDocumentResponse{} }
func (m *PutDocumentResponse) String() string            { return proto.CompactTextString(m) }
func (*PutDocumentResponse) ProtoMessage()               {}
func (*PutDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *PutDocumentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutDocumentResponse) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type GetDocumentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetDocumentRequest) Reset()                    { *m = GetDocumentRequest{} }
func (m *GetDocumentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDocumentRequest) ProtoMessage()               {}
func (*GetDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *GetDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetDocumentResponse struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *GetDocumentResponse) Reset()                    { *m = GetDocumentResponse{} }
func (m *GetDocumentResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDocumentResponse) ProtoMessage()               {}
func (*GetDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *GetDocumentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetDocumentResponse) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type DeleteDocumentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteDocumentRequest) Reset()                    { *m = DeleteDocumentRequest{} }
func (m *DeleteDocumentRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDocumentRequest) ProtoMessage()               {}
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *DeleteDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteDocumentResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteDocumentResponse) Reset()                    { *m = DeleteDocumentResponse{} }
func (m *DeleteDocumentResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteDocumentResponse) ProtoMessage()               {}
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *DeleteDocumentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type BulkRequest struct {
	BatchSize      int32                        `protobuf:"varint,1,opt,name=batch_size,json=batchSize" json:"batch_size,omitempty"`
	UpdateRequests []*BulkRequest_UpdateRequest `protobuf:"bytes,2,rep,name=update_requests,json=updateRequests" json:"update_requests,omitempty"`
}

func (m *BulkRequest) Reset()                    { *m = BulkRequest{} }
func (m *BulkRequest) String() string            { return proto.CompactTextString(m) }
func (*BulkRequest) ProtoMessage()               {}
func (*BulkRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *BulkRequest) GetBatchSize() int32 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

func (m *BulkRequest) GetUpdateRequests() []*BulkRequest_UpdateRequest {
	if m != nil {
		return m.UpdateRequests
	}
	return nil
}

type BulkRequest_UpdateRequest struct {
	Method   string                              `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Document *BulkRequest_UpdateRequest_Document `protobuf:"bytes,2,opt,name=document" json:"document,omitempty"`
}

func (m *BulkRequest_UpdateRequest) Reset()                    { *m = BulkRequest_UpdateRequest{} }
func (m *BulkRequest_UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*BulkRequest_UpdateRequest) ProtoMessage()               {}
func (*BulkRequest_UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9, 0} }

func (m *BulkRequest_UpdateRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *BulkRequest_UpdateRequest) GetDocument() *BulkRequest_UpdateRequest_Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type BulkRequest_UpdateRequest_Document struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *BulkRequest_UpdateRequest_Document) Reset()         { *m = BulkRequest_UpdateRequest_Document{} }
func (m *BulkRequest_UpdateRequest_Document) String() string { return proto.CompactTextString(m) }
func (*BulkRequest_UpdateRequest_Document) ProtoMessage()    {}
func (*BulkRequest_UpdateRequest_Document) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{9, 0, 0}
}

func (m *BulkRequest_UpdateRequest_Document) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BulkRequest_UpdateRequest_Document) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type BulkResponse struct {
	PutCount         int32 `protobuf:"varint,1,opt,name=put_count,json=putCount" json:"put_count,omitempty"`
	PutErrorCount    int32 `protobuf:"varint,2,opt,name=put_error_count,json=putErrorCount" json:"put_error_count,omitempty"`
	DeleteCount      int32 `protobuf:"varint,3,opt,name=delete_count,json=deleteCount" json:"delete_count,omitempty"`
	MethodErrorCount int32 `protobuf:"varint,4,opt,name=method_error_count,json=methodErrorCount" json:"method_error_count,omitempty"`
}

func (m *BulkResponse) Reset()                    { *m = BulkResponse{} }
func (m *BulkResponse) String() string            { return proto.CompactTextString(m) }
func (*BulkResponse) ProtoMessage()               {}
func (*BulkResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *BulkResponse) GetPutCount() int32 {
	if m != nil {
		return m.PutCount
	}
	return 0
}

func (m *BulkResponse) GetPutErrorCount() int32 {
	if m != nil {
		return m.PutErrorCount
	}
	return 0
}

func (m *BulkResponse) GetDeleteCount() int32 {
	if m != nil {
		return m.DeleteCount
	}
	return 0
}

func (m *BulkResponse) GetMethodErrorCount() int32 {
	if m != nil {
		return m.MethodErrorCount
	}
	return 0
}

type SearchRequest struct {
	SearchRequest *google_protobuf.Any `protobuf:"bytes,1,opt,name=search_request,json=searchRequest" json:"search_request,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *SearchRequest) GetSearchRequest() *google_protobuf.Any {
	if m != nil {
		return m.SearchRequest
	}
	return nil
}

type SearchResponse struct {
	SearchResult *google_protobuf.Any `protobuf:"bytes,1,opt,name=search_result,json=searchResult" json:"search_result,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *SearchResponse) GetSearchResult() *google_protobuf.Any {
	if m != nil {
		return m.SearchResult
	}
	return nil
}

type PutNodeRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Node    string `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
}

func (m *PutNodeRequest) Reset()                    { *m = PutNodeRequest{} }
func (m *PutNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*PutNodeRequest) ProtoMessage()               {}
func (*PutNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *PutNodeRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *PutNodeRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type GetNodeRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Node    string `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
}

func (m *GetNodeRequest) Reset()                    { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()               {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *GetNodeRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *GetNodeRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type GetNodeResponse struct {
	Value *google_protobuf.Any `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *GetNodeResponse) Reset()                    { *m = GetNodeResponse{} }
func (m *GetNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNodeResponse) ProtoMessage()               {}
func (*GetNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *GetNodeResponse) GetValue() *google_protobuf.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type DeleteNodeRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Node    string `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
}

func (m *DeleteNodeRequest) Reset()                    { *m = DeleteNodeRequest{} }
func (m *DeleteNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteNodeRequest) ProtoMessage()               {}
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *DeleteNodeRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *DeleteNodeRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func init() {
	proto.RegisterType((*GetIndexPathResponse)(nil), "blast.GetIndexPathResponse")
	proto.RegisterType((*GetIndexMappingResponse)(nil), "blast.GetIndexMappingResponse")
	proto.RegisterType((*GetIndexMetaResponse)(nil), "blast.GetIndexMetaResponse")
	proto.RegisterType((*PutDocumentRequest)(nil), "blast.PutDocumentRequest")
	proto.RegisterType((*PutDocumentResponse)(nil), "blast.PutDocumentResponse")
	proto.RegisterType((*GetDocumentRequest)(nil), "blast.GetDocumentRequest")
	proto.RegisterType((*GetDocumentResponse)(nil), "blast.GetDocumentResponse")
	proto.RegisterType((*DeleteDocumentRequest)(nil), "blast.DeleteDocumentRequest")
	proto.RegisterType((*DeleteDocumentResponse)(nil), "blast.DeleteDocumentResponse")
	proto.RegisterType((*BulkRequest)(nil), "blast.BulkRequest")
	proto.RegisterType((*BulkRequest_UpdateRequest)(nil), "blast.BulkRequest.UpdateRequest")
	proto.RegisterType((*BulkRequest_UpdateRequest_Document)(nil), "blast.BulkRequest.UpdateRequest.Document")
	proto.RegisterType((*BulkResponse)(nil), "blast.BulkResponse")
	proto.RegisterType((*SearchRequest)(nil), "blast.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "blast.SearchResponse")
	proto.RegisterType((*PutNodeRequest)(nil), "blast.PutNodeRequest")
	proto.RegisterType((*GetNodeRequest)(nil), "blast.GetNodeRequest")
	proto.RegisterType((*GetNodeResponse)(nil), "blast.GetNodeResponse")
	proto.RegisterType((*DeleteNodeRequest)(nil), "blast.DeleteNodeRequest")
}

func init() { proto.RegisterFile("pb/message.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 601 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0x6d, 0x4f, 0xd4, 0x40,
	0x10, 0xce, 0x1d, 0xaf, 0x37, 0xf7, 0x02, 0xae, 0x88, 0xe7, 0x11, 0x12, 0x6c, 0x8c, 0xa2, 0x21,
	0x25, 0xc1, 0xf8, 0xc1, 0x18, 0x4d, 0x40, 0x08, 0x12, 0xc5, 0x90, 0x82, 0x5f, 0xfc, 0x72, 0xd9,
	0xb6, 0x43, 0xaf, 0xb1, 0xd7, 0x5d, 0xbb, 0xbb, 0xc6, 0x23, 0xf1, 0xdf, 0xf8, 0x0b, 0xfc, 0xe4,
	0xcf, 0x33, 0xdd, 0x97, 0x72, 0x87, 0x7a, 0x24, 0xe2, 0xb7, 0xce, 0xcc, 0xf3, 0x3c, 0xf3, 0xcc,
	0x4c, 0xba, 0xb0, 0xcc, 0xc3, 0xed, 0x21, 0x0a, 0x41, 0x13, 0xf4, 0x79, 0xc1, 0x24, 0x23, 0x73,
	0x61, 0x46, 0x85, 0xec, 0xdd, 0x4b, 0x18, 0x4b, 0x32, 0xdc, 0xd6, 0xc9, 0x50, 0x9d, 0x6f, 0xd3,
	0x7c, 0x64, 0x10, 0xbd, 0xb5, 0xab, 0x25, 0x1c, 0x72, 0x69, 0x8b, 0xde, 0x33, 0x58, 0x39, 0x44,
	0x79, 0x94, 0xc7, 0xf8, 0xf5, 0x84, 0xca, 0x41, 0x80, 0x82, 0xb3, 0x5c, 0x20, 0x59, 0x07, 0x48,
	0xcb, 0x64, 0x9f, 0x53, 0x39, 0xe8, 0xd6, 0x36, 0x6a, 0x9b, 0x8d, 0xa0, 0x91, 0x3a, 0x98, 0x77,
	0x06, 0x77, 0x1d, 0xed, 0x98, 0x72, 0x9e, 0xe6, 0x49, 0xc5, 0x7c, 0x0e, 0x6d, 0xc3, 0x1c, 0x9a,
	0x82, 0x26, 0x37, 0x77, 0x56, 0x7c, 0x63, 0xc3, 0x77, 0x36, 0xfc, 0xdd, 0x7c, 0x14, 0xb4, 0xd2,
	0x31, 0x09, 0xef, 0xdb, 0xa5, 0x99, 0x63, 0x94, 0xf4, 0x77, 0x33, 0x72, 0xc4, 0x71, 0xc2, 0xcc,
	0xd9, 0x88, 0x23, 0xe9, 0xc2, 0x82, 0x90, 0xac, 0xa0, 0x09, 0x76, 0xeb, 0xba, 0xe6, 0x42, 0xb2,
	0x05, 0xf3, 0x11, 0xcb, 0xcf, 0xd3, 0xa4, 0x3b, 0x33, 0xc5, 0x84, 0xc5, 0x78, 0x01, 0x90, 0x13,
	0x25, 0xf7, 0x59, 0xa4, 0x86, 0x98, 0xcb, 0x00, 0x3f, 0x2b, 0x14, 0x92, 0x74, 0xa0, 0x9e, 0xc6,
	0xb6, 0x69, 0x3d, 0x8d, 0x4b, 0xcd, 0xf3, 0x14, 0xb3, 0x58, 0xe8, 0x66, 0x7f, 0xd5, 0x34, 0x18,
	0xef, 0x14, 0x6e, 0x4f, 0x68, 0xda, 0x89, 0x6e, 0x26, 0xfa, 0x00, 0xc8, 0x21, 0x5e, 0x67, 0xb4,
	0x6c, 0x3d, 0x81, 0xfa, 0x2f, 0xad, 0x1f, 0xc1, 0x9d, 0x7d, 0xcc, 0x50, 0xe2, 0x75, 0xdd, 0x37,
	0x61, 0xf5, 0x2a, 0xf0, 0xcf, 0x06, 0xbc, 0x1f, 0x75, 0x68, 0xee, 0xa9, 0xec, 0x93, 0x53, 0x5a,
	0x07, 0x08, 0xa9, 0x8c, 0x06, 0x7d, 0x91, 0x5e, 0x98, 0x6b, 0xcf, 0x05, 0x0d, 0x9d, 0x39, 0x4d,
	0x2f, 0x90, 0x1c, 0xc1, 0x92, 0xe2, 0x31, 0x95, 0xd8, 0x2f, 0x0c, 0xa1, 0x34, 0x3e, 0xb3, 0xd9,
	0xdc, 0xd9, 0xf0, 0xf5, 0xaf, 0xe0, 0x8f, 0x69, 0xf9, 0x1f, 0x34, 0xd2, 0x46, 0x41, 0x47, 0x8d,
	0x87, 0xa2, 0xf7, 0xb3, 0x06, 0xed, 0x09, 0x04, 0x59, 0x85, 0xf9, 0x21, 0xca, 0x01, 0x73, 0xfe,
	0x6c, 0x44, 0x0e, 0x60, 0x31, 0xb6, 0x73, 0xd8, 0x35, 0x3d, 0xbe, 0xae, 0x9b, 0x5f, 0x0d, 0x5e,
	0x51, 0x7b, 0x6f, 0x60, 0xd1, 0x65, 0x6f, 0x78, 0x87, 0xef, 0x35, 0x68, 0x99, 0xd6, 0x76, 0xab,
	0x6b, 0xd0, 0xe0, 0x4a, 0xf6, 0x23, 0xa6, 0x72, 0x69, 0x97, 0xb6, 0xc8, 0x95, 0x7c, 0x5d, 0xc6,
	0xe4, 0x21, 0x2c, 0x95, 0x45, 0x2c, 0x0a, 0x56, 0x58, 0x48, 0x5d, 0x43, 0xda, 0x5c, 0xc9, 0x83,
	0x32, 0x6b, 0x70, 0xf7, 0xa1, 0x15, 0xeb, 0xa3, 0x59, 0xd0, 0x8c, 0x06, 0x35, 0x4d, 0xce, 0x40,
	0xb6, 0x80, 0x98, 0x9d, 0x4c, 0xa8, 0xcd, 0x6a, 0xe0, 0xb2, 0xa9, 0x5c, 0x0a, 0x7a, 0xef, 0xa0,
	0x7d, 0x8a, 0xb4, 0x88, 0x06, 0x6e, 0xc1, 0x2f, 0xa0, 0x23, 0x74, 0xc2, 0x5d, 0x6f, 0xea, 0xf3,
	0xd0, 0x16, 0xe3, 0x64, 0xef, 0x2d, 0x74, 0x9c, 0xda, 0xe5, 0x63, 0x53, 0xc9, 0x09, 0x95, 0x4d,
	0x57, 0x6b, 0x39, 0xb5, 0x12, 0xe9, 0xbd, 0x82, 0xce, 0x89, 0x92, 0xef, 0x59, 0x5c, 0x1d, 0xbf,
	0x0b, 0x0b, 0x51, 0xa6, 0x84, 0xc4, 0xc2, 0x9e, 0xc5, 0x85, 0x84, 0xc0, 0x6c, 0xce, 0x62, 0xf7,
	0xbc, 0xe8, 0xef, 0x92, 0x7f, 0x88, 0x37, 0xe0, 0xbf, 0x84, 0xa5, 0x8a, 0x6f, 0xa7, 0x79, 0x02,
	0x73, 0x5f, 0x68, 0xa6, 0x70, 0xea, 0x14, 0x06, 0xe2, 0xed, 0xc2, 0x2d, 0xf3, 0x7f, 0xfd, 0xb3,
	0x83, 0xbd, 0xd9, 0x8f, 0x75, 0x1e, 0x86, 0xf3, 0x5a, 0xfd, 0xe9, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x51, 0x76, 0x42, 0xca, 0x5b, 0x06, 0x00, 0x00,
}
